export const colors = {
  background: 'transparent',
  primary: '#2F80ED',
  accent: '#4B96F3',
  surface: '#FFFFFF',
  success: '#0A9B67',
  warning: '#F59E0B',
  danger: '#E84A5F',
  text: '#152033',
  textSecondary: '#607086',
  textMuted: '#8B98AA',
  border: '#E4EAF2',
  successSoft: '#E7F7F0',
  warningSoft: '#FFF3DE',
  dangerSoft: '#FDECEF',
  accentSoft: '#EAF3FF',
  pressed: '#EDF5FF',
} as const;
