import { Ionicons } from '@expo/vector-icons';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { router } from 'expo-router';
import type { ComponentProps } from 'react';
import { useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../../src/api';
import { useAuthStore } from '../../src/auth-store';
import { notificationDeepLink } from '../../src/consumer-error-presenter';
import { messageChannel, type MessageChannelFilter } from '../../src/message-presenter';
import { EmptyState, workspaceColors as colors, radius, spacing, typography } from '../../src/design';

type IconName = ComponentProps<typeof Ionicons>['name'];
interface NotificationRow { id: string; title: string; body: string; status: string; eventType: string; createdAt: string; executionId?: string | null; approvalRequestId?: string | null; connectionId?: string | null }
const CHANNELS: Array<{ key: MessageChannelFilter; label: string }> = [{ key: 'all', label: '全部' }, { key: 'plan', label: '计划动态' }, { key: 'system', label: '系统通知' }];

export default function MessagesPage() {
  const token = useAuthStore((store) => store.token);
  const client = useQueryClient();
  const [channel, setChannel] = useState<MessageChannelFilter>('all');
  const [searchOpen, setSearchOpen] = useState(false);
  const [query, setQuery] = useState('');
  const messages = useQuery({ queryKey: ['notifications', token], queryFn: () => api<NotificationRow[]>('/notifications', token), enabled: Boolean(token) });
  const unread = useQuery({ queryKey: ['notifications-unread', token], queryFn: () => api<{ count: number }>('/notifications/unread-count', token), enabled: Boolean(token) });
  const markRead = useMutation({ mutationFn: (id: string) => api(`/notifications/${id}/read`, token, { method: 'POST' }), onSuccess: async () => { await Promise.all([client.invalidateQueries({ queryKey: ['notifications', token] }), client.invalidateQueries({ queryKey: ['notifications-unread', token] })]); } });
  const rows = useMemo(() => {
    const normalized = query.trim().toLocaleLowerCase('zh-CN');
    return (messages.data ?? []).filter((item) => channel === 'all' || messageChannel(item.eventType) === channel).filter((item) => !normalized || `${item.title} ${item.body}`.toLocaleLowerCase('zh-CN').includes(normalized));
  }, [messages.data, channel, query]);
  const grouped = useMemo(() => groupMessages(rows), [rows]);
  function open(item: NotificationRow) { if (item.status === 'unread') markRead.mutate(item.id); const route = notificationDeepLink({ eventType: item.eventType, executionId: item.executionId, approvalRequestId: item.approvalRequestId, connectionId: item.connectionId, reconciliationCaseId: null }); if (route) router.push(route as never); }

  return <SafeAreaView edges={[]} style={styles.safeArea}><ScrollView contentContainerStyle={styles.content} refreshControl={token ? <RefreshControl refreshing={messages.isFetching} onRefresh={() => { messages.refetch(); unread.refetch(); }} tintColor={colors.primary} /> : undefined}>
    <View style={styles.header}><View style={styles.titleRow}><Text style={styles.title}>消息</Text>{(unread.data?.count ?? 0) > 0 ? <View style={styles.unreadBadge}><Text style={styles.unreadText}>{unread.data!.count > 99 ? '99+' : unread.data!.count}</Text></View> : null}</View><Pressable accessibilityRole="button" onPress={() => setSearchOpen((value) => !value)} style={({ pressed }) => [styles.searchAction, pressed && styles.pressed]}><Ionicons name="search-outline" size={23} color={colors.text} /><Text style={styles.searchActionText}>搜索</Text></Pressable></View>
    {searchOpen ? <View style={styles.searchBox}><Ionicons name="search-outline" size={19} color={colors.textMuted} /><TextInput autoFocus value={query} onChangeText={setQuery} placeholder="搜索消息" placeholderTextColor={colors.textMuted} style={styles.searchInput} />{query ? <Pressable onPress={() => setQuery('')}><Ionicons name="close-circle" size={19} color={colors.textMuted} /></Pressable> : null}</View> : null}
    {token ? <View style={styles.tabs}>{CHANNELS.map((item) => <Pressable key={item.key} accessibilityRole="tab" accessibilityState={{ selected: channel === item.key }} onPress={() => setChannel(item.key)} style={[styles.tab, channel === item.key && styles.tabActive]}><Text style={[styles.tabText, channel === item.key && styles.tabTextActive]}>{item.label}</Text></Pressable>)}</View> : null}
    {!token ? <EmptyState icon="notifications-outline" title="登录后查看消息" /> : null}
    {messages.isLoading ? <View style={styles.loading}><ActivityIndicator color={colors.primary} /><Text style={styles.loadingText}>正在读取消息…</Text></View> : null}
    {messages.isError ? <EmptyState icon="cloud-offline-outline" title="消息暂时不可用" action={{ label: '重新加载', onPress: () => messages.refetch() }} /> : null}
    {!messages.isLoading && !messages.isError && messages.data && rows.length === 0 ? <EmptyState icon="notifications-off-outline" title={query ? '没有匹配的消息' : '还没有消息'} description="计划和系统产生真实事件后会显示在这里。" /> : null}
    {grouped.map((group) => <View key={group.label}><Text style={styles.groupTitle}>{group.label}</Text><View style={styles.group}>{group.items.map((item) => <MessageCard key={item.id} item={item} onPress={() => open(item)} />)}</View></View>)}
  </ScrollView></SafeAreaView>;
}

function MessageCard({ item, onPress }: { item: NotificationRow; onPress: () => void }) { const visual = messageVisual(item); return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={[styles.cardIcon, { backgroundColor: visual.background }]}><Ionicons name={visual.icon} size={24} color={visual.color} /></View><View style={styles.cardCopy}><Text numberOfLines={1} style={styles.cardTitle}>{item.title}</Text><Text numberOfLines={2} style={styles.cardBody}>{item.body}</Text></View><View style={styles.cardMeta}><Text style={styles.cardTime}>{formatTime(item.createdAt)}</Text>{item.status === 'unread' ? <View style={styles.dot} /> : null}</View><Ionicons name="chevron-forward" size={19} color={colors.textSecondary} /></Pressable>; }
function messageVisual(item: NotificationRow): { icon: IconName; color: string; background: string } { const text = `${item.eventType} ${item.title}`.toLowerCase(); if (text.includes('deliver') || text.includes('快递')) return { icon: 'bus-outline', color: colors.primary, background: colors.accentSoft }; if (text.includes('supply') || text.includes('补给')) return { icon: 'cart-outline', color: '#C97917', background: '#FFF2DE' }; if (text.includes('device') || text.includes('设备')) return { icon: 'settings-outline', color: '#3474C8', background: '#EAF2FD' }; if (messageChannel(item.eventType) === 'system') return { icon: 'notifications-outline', color: colors.primary, background: colors.accentSoft }; return { icon: 'calendar-outline', color: '#7754B8', background: '#F0EBFA' }; }
function groupMessages(items: NotificationRow[]) { const groups = new Map<string, NotificationRow[]>(); for (const item of items) { const label = dayLabel(item.createdAt); groups.set(label, [...(groups.get(label) ?? []), item]); } return [...groups.entries()].map(([label, groupItems]) => ({ label, items: groupItems })); }
function dayLabel(value: string) { const date = new Date(value); if (Number.isNaN(date.getTime())) return '更早'; const today = new Date(); const startToday = new Date(today.getFullYear(), today.getMonth(), today.getDate()).getTime(); const startDate = new Date(date.getFullYear(), date.getMonth(), date.getDate()).getTime(); const days = Math.round((startToday - startDate) / 86_400_000); return days === 0 ? '今天' : days === 1 ? '昨天' : '更早'; }
function formatTime(value: string) { const date = new Date(value); if (Number.isNaN(date.getTime())) return ''; const label = dayLabel(value); return label === '今天' ? date.toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' }) : label === '昨天' ? `昨天 ${date.toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })}` : date.toLocaleString('zh-CN', { month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit' }); }

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background }, content: { paddingHorizontal: spacing.lg, paddingTop: spacing.md, paddingBottom: 92 }, pressed: { opacity: 0.68 }, header: { minHeight: 58, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, titleRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, title: { ...typography.pageTitle, color: colors.text }, unreadBadge: { minWidth: 20, height: 20, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 5, borderRadius: 10, backgroundColor: colors.danger }, unreadText: { color: '#FFFFFF', fontSize: 12, fontWeight: '800' }, searchAction: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 6 }, searchActionText: { ...typography.caption, color: colors.text, fontWeight: '700' }, searchBox: { minHeight: 46, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginBottom: spacing.sm, paddingHorizontal: spacing.md, borderRadius: radius.pill, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, searchInput: { flex: 1, ...typography.body, color: colors.text, paddingVertical: 8 }, tabs: { minHeight: 54, flexDirection: 'row', marginTop: spacing.sm, padding: 4, borderRadius: radius.pill, backgroundColor: '#EFEEEA' }, tab: { flex: 1, alignItems: 'center', justifyContent: 'center', borderRadius: radius.pill }, tabActive: { backgroundColor: colors.surface, elevation: 1 }, tabText: { ...typography.caption, color: colors.textSecondary, fontWeight: '700' }, tabTextActive: { color: colors.text }, loading: { minHeight: 180, alignItems: 'center', justifyContent: 'center', gap: spacing.sm }, loadingText: { ...typography.caption, color: colors.textSecondary }, groupTitle: { ...typography.section, color: colors.textSecondary, fontSize: 17, lineHeight: 24, marginTop: spacing.lg, marginBottom: spacing.sm }, group: { gap: spacing.sm }, card: { minHeight: 86, flexDirection: 'row', alignItems: 'center', gap: spacing.md, padding: spacing.md, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, shadowColor: '#625A50', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 7, elevation: 1 }, cardIcon: { width: 52, height: 52, alignItems: 'center', justifyContent: 'center', borderRadius: 18 }, cardCopy: { flex: 1, minWidth: 0 }, cardTitle: { ...typography.bodyStrong, color: colors.text }, cardBody: { ...typography.caption, color: colors.textSecondary, lineHeight: 18, marginTop: 3 }, cardMeta: { alignItems: 'flex-end', gap: 8 }, cardTime: { fontSize: 12, color: colors.textMuted }, dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#F05A5A' },
});
