import { Ionicons } from '@expo/vector-icons';
import { useQuery } from '@tanstack/react-query';
import { router } from 'expo-router';
import type { ComponentProps } from 'react';
import { useMemo, useState } from 'react';
import { ActivityIndicator, Image, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../../src/api';
import { useAuthStore } from '../../src/auth-store';
import { discoverLaunchableApps, type DiscoveredDeviceApp } from '../../src/device-app-bridge';

type IconName = ComponentProps<typeof Ionicons>['name'];
type ResourceTab = 'local' | 'cloud' | 'devices' | 'api';
interface Connection { id: string; connectorId: string; connectorName: string; connectorDescription: string; externalAccountName: string; status: string }
interface Device { id: string; type: string; brand: string; model: string; sourceType: string }
interface Connector { key: string; name: string; description: string; connectable: boolean; productionStatus: string }
interface DeviceAppConnection { id: string; packageName: string; displayName: string; enabled: boolean }

const COLORS = ['#FF466A', '#F4A62A', '#754CE9', '#FF7D2D', '#10B4A5', '#1678EE', '#7C4FE8', '#13B96D'] as const;

export default function ResourcesPage() {
  const token = useAuthStore((store) => store.token);
  const [tab, setTab] = useState<ResourceTab>('local');
  const connections = useQuery({ queryKey: ['resources-connections', token], queryFn: () => api<Connection[]>('/connections', token), enabled: Boolean(token) });
  const deviceApps = useQuery({ queryKey: ['device-app-connections', token], queryFn: () => api<DeviceAppConnection[]>('/device-app-connections', token), enabled: Boolean(token) });
  const devices = useQuery({ queryKey: ['resources-devices', token], queryFn: () => api<Device[]>('/device-profiles', token), enabled: Boolean(token) });
  const connectors = useQuery({ queryKey: ['resource-connectors'], queryFn: () => api<Connector[]>('/connectors') });
  const discovered = useQuery({ queryKey: ['resources-discovered-apps'], queryFn: discoverLaunchableApps, enabled: Boolean(token), staleTime: 5 * 60_000 });
  const connectedPackages = useMemo(() => new Map((deviceApps.data ?? []).map((item) => [item.packageName, item])), [deviceApps.data]);
  const refresh = () => { void Promise.all([connections.refetch(), deviceApps.refetch(), devices.refetch(), connectors.refetch(), discovered.refetch()]); };
  const loading = connections.isLoading || deviceApps.isLoading || devices.isLoading || discovered.isLoading;

  return <SafeAreaView edges={['top']} style={styles.safeArea}>
    <View style={styles.header}><View><Text style={styles.pageTitle}>资源</Text><Text style={styles.pageSubtitle}>管理应用、数据、设备与授权</Text></View><Pressable accessibilityRole="button" accessibilityLabel="添加资源" onPress={() => router.push('/connections/add' as never)} style={({ pressed }) => [styles.addResource, pressed && styles.pressed]}><Ionicons name="add" size={19} color="#1769E0" /><Text style={styles.addResourceText}>添加资源</Text></Pressable></View>
    <View style={styles.tabs}><Tab label={`本机 · ${discovered.data?.length ?? 0}`} selected={tab === 'local'} onPress={() => setTab('local')} /><Tab label={`云端 · ${connectors.data?.length ?? 0}`} selected={tab === 'cloud'} onPress={() => setTab('cloud')} /><Tab label={`其它设备 · ${devices.data?.length ?? 0}`} selected={tab === 'devices'} onPress={() => setTab('devices')} /><Tab label="接口" selected={tab === 'api'} onPress={() => setTab('api')} /></View>
    <ScrollView contentContainerStyle={styles.content} refreshControl={token ? <RefreshControl tintColor="#287CEB" refreshing={connections.isFetching || deviceApps.isFetching || devices.isFetching} onRefresh={refresh} /> : undefined}>
      {!token ? <State title="登录后管理资源" detail="应用、设备和授权只对当前账号可见。" action="去登录" onPress={() => router.push('/auth/login' as never)} /> : null}
      {token && loading ? <View style={styles.loading}><ActivityIndicator color="#287CEB" /><Text style={styles.muted}>正在读取真实资源…</Text></View> : null}
      {token && !loading && tab === 'local' ? <View style={styles.list}>{(discovered.data ?? []).map((app, index) => <LocalRow key={app.packageName} app={app} connected={connectedPackages.get(app.packageName)} index={index} />)}{(discovered.data?.length ?? 0) === 0 ? <State title="没有读取到本机应用" detail="请使用包含原生设备模块的 Android 构建。" action="重试" onPress={refresh} /> : null}</View> : null}
      {token && !loading && tab === 'cloud' ? <View style={styles.list}>{(connectors.data ?? []).map((connector, index) => { const connection = (connections.data ?? []).find((item) => item.connectorId === connector.key); return <ResourceRow key={connector.key} index={index} icon={providerIcon(connector.key)} title={connector.name} detail={connection?.externalAccountName || connector.description} status={connection && ['connected', 'active'].includes(connection.status) ? '已连接' : connector.connectable ? '连接' : '未配置'} connected={Boolean(connection && ['connected', 'active'].includes(connection.status))} onPress={() => connection ? router.push(`/connections/${connection.id}` as never) : router.push('/connections' as never)} />; })}</View> : null}
      {token && !loading && tab === 'devices' ? <View style={styles.list}>{(devices.data ?? []).map((device, index) => <ResourceRow key={device.id} index={index} icon="phone-portrait-outline" title={`${device.brand} ${device.model}`.trim() || device.type} detail={`${device.type} · ${device.sourceType === 'manual' ? '手工记录' : '已连接来源'}`} status="查看" onPress={() => router.push(`/devices/${device.id}` as never)} />)}{(devices.data?.length ?? 0) === 0 ? <State title="还没有其它设备" detail="添加设备后会在这里显示真实状态。" action="添加" onPress={() => router.push('/devices' as never)} /> : null}</View> : null}
      {token && !loading && tab === 'api' ? <View style={styles.list}><ResourceRow index={0} icon="shield-checkmark-outline" title="授权管理" detail="检查访问范围、撤销状态与安全边界" status="管理" onPress={() => router.push('/permissions' as never)} /><ResourceRow index={1} icon="flash-outline" title="执行能力" detail="查看计划可调用的设备和扩展能力" status="查看" onPress={() => router.push('/connections' as never)} /><ResourceRow index={2} icon="folder-open-outline" title="数据与知识" detail="文件、事实记录与个人数据" status="管理" onPress={() => router.push('/privacy-center/data' as never)} /></View> : null}
    </ScrollView>
  </SafeAreaView>;
}

function Tab({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable accessibilityRole="tab" accessibilityState={{ selected }} onPress={onPress} style={[styles.tab, selected && styles.tabSelected]}><Text numberOfLines={1} style={[styles.tabText, selected && styles.tabTextSelected]}>{label}</Text></Pressable>; }
function LocalRow({ app, connected, index }: { app: DiscoveredDeviceApp; connected?: DeviceAppConnection; index: number }) { return <Pressable accessibilityRole="button" onPress={() => connected ? router.push('/connections' as never) : router.push('/connections/add' as never)} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><View style={[styles.icon, { backgroundColor: COLORS[index % COLORS.length] }]}>{app.iconDataUri ? <Image source={{ uri: app.iconDataUri }} style={styles.appImage} /> : <Ionicons name="apps-outline" size={27} color="#FFFFFF" />}</View><View style={styles.copy}><Text style={styles.title}>{app.displayName}</Text><Text numberOfLines={1} style={styles.detail}>{connected ? '已保存为本机应用连接' : '这台手机上已安装的应用'}</Text></View><Status connected={Boolean(connected?.enabled)} label={connected?.enabled ? '已连接' : '连接'} /></Pressable>; }
function ResourceRow({ index, icon, title, detail, status, connected = false, onPress }: { index: number; icon: IconName; title: string; detail: string; status: string; connected?: boolean; onPress: () => void }) { return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><View style={[styles.icon, { backgroundColor: COLORS[index % COLORS.length] }]}><Ionicons name={icon} size={27} color="#FFFFFF" /></View><View style={styles.copy}><Text style={styles.title}>{title}</Text><Text numberOfLines={1} style={styles.detail}>{detail}</Text></View><Status connected={connected} label={status} /></Pressable>; }
function Status({ connected, label }: { connected: boolean; label: string }) { return <View style={[styles.status, connected && styles.statusConnected]}>{connected ? <Ionicons name="checkmark-circle" size={18} color="#0BAA62" /> : null}<Text style={[styles.statusText, connected && styles.statusTextConnected]}>{label}</Text></View>; }
function State({ title, detail, action, onPress }: { title: string; detail: string; action: string; onPress: () => void }) { return <View style={styles.state}><View style={styles.copy}><Text style={styles.title}>{title}</Text><Text style={styles.detail}>{detail}</Text></View><Pressable onPress={onPress} style={styles.status}><Text style={styles.statusText}>{action}</Text></Pressable></View>; }
function providerIcon(key: string): IconName { if (/mail|gmail/.test(key)) return 'mail-outline'; if (/calendar/.test(key)) return 'calendar-outline'; if (/github/.test(key)) return 'logo-github'; if (/feishu|dingtalk|wecom/.test(key)) return 'chatbubbles-outline'; return 'cloud-outline'; }

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: 'rgba(248,250,253,0.90)' }, header: { minHeight: 82, flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', paddingHorizontal: 18, paddingTop: 18 }, pageTitle: { color: '#111827', fontSize: 30, lineHeight: 37, fontWeight: '700' }, pageSubtitle: { marginTop: 2, color: '#6B7788', fontSize: 14, lineHeight: 20 }, addResource: { minHeight: 40, flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 13, borderRadius: 12, borderWidth: StyleSheet.hairlineWidth, borderColor: '#D8E2F0', backgroundColor: '#FFFFFF' }, addResourceText: { color: '#1769E0', fontSize: 14, fontWeight: '600' }, tabs: { flexDirection: 'row', paddingHorizontal: 18, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#DCE3EC' }, tab: { flex: 1, minHeight: 43, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4, borderBottomWidth: 2, borderBottomColor: 'transparent' }, tabSelected: { borderBottomColor: '#2F80ED' }, tabText: { color: '#667386', fontSize: 13 }, tabTextSelected: { color: '#162033', fontWeight: '600' }, content: { paddingHorizontal: 18, paddingTop: 14, paddingBottom: 24 }, list: { overflow: 'hidden', borderRadius: 16, borderWidth: StyleSheet.hairlineWidth, borderColor: '#DEE6EF', backgroundColor: 'rgba(255,255,255,0.94)' }, row: { minHeight: 78, flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 13, paddingVertical: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#E7ECF2' }, icon: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center', overflow: 'hidden', borderRadius: 13 }, appImage: { width: 48, height: 48 }, copy: { flex: 1, minWidth: 0 }, title: { color: '#162033', fontSize: 16, lineHeight: 22, fontWeight: '600' }, detail: { marginTop: 2, color: '#697688', fontSize: 13, lineHeight: 19 }, status: { minHeight: 32, flexDirection: 'row', alignItems: 'center', gap: 4, justifyContent: 'center', paddingHorizontal: 5 }, statusConnected: {}, statusText: { color: '#1769E0', fontSize: 13, fontWeight: '600' }, statusTextConnected: { color: '#0A9B67' }, loading: { minHeight: 180, alignItems: 'center', justifyContent: 'center', gap: 10 }, muted: { color: '#657184', fontSize: 14 }, state: { minHeight: 82, flexDirection: 'row', alignItems: 'center', gap: 10, padding: 14, borderRadius: 16, borderWidth: StyleSheet.hairlineWidth, borderColor: '#DEE6EF', backgroundColor: '#FFFFFF' }, pressed: { opacity: 0.65 },
});
