import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import type { ComponentProps } from 'react';
import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { workspaceColors as colors, radius, spacing, typography } from '../../src/design';

type IconName = ComponentProps<typeof Ionicons>['name'];
const PRIVACY_STATUS: Array<{ icon: IconName; title: string; detail: string; state: string; tone: 'safe' | 'warning' | 'muted'; route: string }> = [
  { icon: 'search-outline', title: '搜索隔离', detail: '私密内容默认不参与全局搜索。', state: '建设中', tone: 'warning', route: '/privacy-center/data' },
  { icon: 'sparkles-outline', title: 'AI 隔离', detail: '未明确授权前不进入 AI 读取。', state: '建设中', tone: 'warning', route: '/privacy-center/ai' },
  { icon: 'lock-closed-outline', title: '独立解锁', detail: '专门解锁与恢复验证尚未完成。', state: '尚未开放', tone: 'muted', route: '/security-center' },
  { icon: 'document-text-outline', title: '授权记录', detail: '查看已有连接、审批和重要操作。', state: '可查看', tone: 'safe', route: '/security-activity' },
];
const PROTECTED_OBJECTS: Array<{ icon: IconName; title: string; detail: string; route: string }> = [
  { icon: 'person-outline', title: '身份信息', detail: '证件、护照、户口本等个人身份资料。', route: '/data-management' },
  { icon: 'heart-outline', title: '家庭健康', detail: '家人健康信息、病历与体检资料。', route: '/data-management' },
  { icon: 'wallet-outline', title: '财务资料', detail: '账单、合同和理财信息等。', route: '/privacy-center/data' },
  { icon: 'document-outline', title: '重要文件', detail: '个人文件、证件与合同等资料。', route: '/data-management' },
];

export default function PrivateSpacePage() {
  const [tab, setTab] = useState<'mine' | 'authorized'>('mine');
  return <SafeAreaView edges={[]} style={styles.safeArea}><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.header}><Text style={styles.title}>私密</Text><View style={styles.headerActions}><HeaderAction icon="search-outline" label="搜索" onPress={() => router.push('/privacy-center/data' as never)} /><View style={styles.headerDivider} /><HeaderAction icon="shield-checkmark-outline" label="授权" onPress={() => router.push('/permissions' as never)} /></View></View>
    <View style={styles.hero}><View style={styles.heroIcon}><Ionicons name="shield-checkmark-outline" size={54} color={colors.primary} /><Ionicons name="lock-closed" size={22} color={colors.primary} style={styles.heroLock} /></View><View style={styles.heroCopy}><Text style={styles.heroTitle}>私密空间</Text><Text style={styles.heroText}>仅在你明确授权后访问，不默认参与搜索与 AI 读取。</Text><View style={styles.buildBadge}><Text style={styles.buildBadgeText}>功能建设中</Text></View></View></View>
    <View style={styles.segment}><Segment label="我的私密" active={tab === 'mine'} onPress={() => setTab('mine')} /><Segment label="授权访问" active={tab === 'authorized'} onPress={() => setTab('authorized')} /></View>
    {tab === 'mine' ? <><SectionTitle>隐私状态</SectionTitle><View style={styles.group}>{PRIVACY_STATUS.map((item, index) => <PrivacyRow key={item.title} {...item} last={index === PRIVACY_STATUS.length - 1} />)}</View><SectionTitle>保护对象</SectionTitle><View style={styles.group}>{PROTECTED_OBJECTS.map((item, index) => <ObjectRow key={item.title} {...item} last={index === PROTECTED_OBJECTS.length - 1} />)}</View><SectionTitle>当前边界</SectionTitle><View style={styles.boundaryCard}><Boundary icon="search-outline" text={'默认不参与\n全局搜索'} /><Boundary icon="sparkles-outline" text={'默认不参与\nAI 读取'} /><Boundary icon="shield-checkmark-outline" text={'关键访问\n需单独确认'} /></View></> : <View style={styles.authorizedCard}><Ionicons name="shield-outline" size={27} color={colors.primary} /><View style={styles.authorizedCopy}><Text style={styles.authorizedTitle}>只显示真实授权记录</Text><Text style={styles.authorizedText}>连接、权限和审批记录由服务端权威状态提供；尚未授权的能力不会显示为可用。</Text></View><Pressable onPress={() => router.push('/permissions' as never)} style={styles.linkButton}><Text style={styles.linkButtonText}>查看授权</Text></Pressable></View>}
    <Pressable accessibilityRole="button" onPress={() => router.push('/privacy-center' as never)} style={({ pressed }) => [styles.primaryButton, pressed && styles.pressed]}><Text style={styles.primaryButtonText}>查看隐私建设与数据边界</Text></Pressable>
  </ScrollView></SafeAreaView>;
}

function HeaderAction({ icon, label, onPress }: { icon: IconName; label: string; onPress: () => void }) { return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.headerAction, pressed && styles.pressed]}><Ionicons name={icon} size={21} color={colors.text} /><Text style={styles.headerActionText}>{label}</Text></Pressable>; }
function Segment({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable accessibilityRole="tab" accessibilityState={{ selected: active }} onPress={onPress} style={[styles.segmentItem, active && styles.segmentActive]}><Text style={[styles.segmentText, active && styles.segmentTextActive]}>{label}</Text></Pressable>; }
function SectionTitle({ children }: { children: string }) { return <Text style={styles.sectionTitle}>{children}</Text>; }
function PrivacyRow({ icon, title, detail, state, tone, route, last }: (typeof PRIVACY_STATUS)[number] & { last: boolean }) { return <Pressable accessibilityRole="button" onPress={() => router.push(route as never)} style={({ pressed }) => [styles.row, !last && styles.rowDivider, pressed && styles.pressed]}><View style={[styles.rowIcon, tone === 'warning' && styles.iconWarning, tone === 'muted' && styles.iconMuted]}><Ionicons name={icon} size={21} color={tone === 'warning' ? '#D97706' : tone === 'muted' ? '#7B6AB2' : colors.primary} /></View><View style={styles.rowCopy}><Text style={styles.rowTitle}>{title}</Text><Text style={styles.rowDetail}>{detail}</Text></View><View style={[styles.stateBadge, tone === 'warning' && styles.stateWarning, tone === 'muted' && styles.stateMuted]}><Text style={[styles.stateText, tone === 'warning' && styles.stateTextWarning, tone === 'muted' && styles.stateTextMuted]}>{state}</Text></View><Ionicons name="chevron-forward" size={17} color={colors.textMuted} /></Pressable>; }
function ObjectRow({ icon, title, detail, route, last }: (typeof PROTECTED_OBJECTS)[number] & { last: boolean }) { return <Pressable accessibilityRole="button" onPress={() => router.push(route as never)} style={({ pressed }) => [styles.row, !last && styles.rowDivider, pressed && styles.pressed]}><View style={styles.rowIcon}><Ionicons name={icon} size={21} color={colors.primary} /></View><View style={styles.rowCopy}><Text style={styles.rowTitle}>{title}</Text><Text style={styles.rowDetail}>{detail}</Text></View><View style={styles.stateMuted}><Text style={styles.stateTextMuted}>待开放</Text></View><Ionicons name="chevron-forward" size={17} color={colors.textMuted} /></Pressable>; }
function Boundary({ icon, text }: { icon: IconName; text: string }) { return <View style={styles.boundary}><View style={styles.boundaryIcon}><Ionicons name={icon} size={22} color={colors.primary} /></View><Text style={styles.boundaryText}>{text}</Text></View>; }

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background }, content: { paddingHorizontal: spacing.lg, paddingTop: spacing.sm, paddingBottom: 92 }, pressed: { opacity: 0.68 }, header: { minHeight: 56, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, title: { ...typography.pageTitle, color: colors.text }, headerActions: { flexDirection: 'row', alignItems: 'center' }, headerAction: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: spacing.sm }, headerActionText: { ...typography.caption, color: colors.text, fontWeight: '700' }, headerDivider: { width: 1, height: 22, backgroundColor: colors.border },
  hero: { minHeight: 122, flexDirection: 'row', alignItems: 'center', gap: spacing.lg, marginTop: spacing.sm, padding: spacing.lg, borderRadius: radius.lg, borderWidth: 1, borderColor: '#D9E5DE', backgroundColor: '#F1F7F3' }, heroIcon: { width: 88, height: 88, alignItems: 'center', justifyContent: 'center', borderRadius: 30, backgroundColor: '#DDEFE6' }, heroLock: { position: 'absolute' }, heroCopy: { flex: 1 }, heroTitle: { ...typography.title, color: colors.text }, heroText: { ...typography.caption, color: colors.textSecondary, lineHeight: 19, marginTop: 4 }, buildBadge: { alignSelf: 'flex-start', marginTop: spacing.sm, paddingHorizontal: 10, paddingVertical: 4, borderRadius: radius.pill, backgroundColor: '#FFF0D8' }, buildBadgeText: { fontSize: 10, fontWeight: '800', color: '#C56C00' },
  segment: { minHeight: 50, flexDirection: 'row', marginTop: spacing.md, padding: 3, borderRadius: radius.pill, backgroundColor: '#EFEEEA' }, segmentItem: { flex: 1, alignItems: 'center', justifyContent: 'center', borderRadius: radius.pill }, segmentActive: { backgroundColor: colors.surface, elevation: 1 }, segmentText: { ...typography.caption, color: colors.textSecondary, fontWeight: '700' }, segmentTextActive: { color: colors.text }, sectionTitle: { ...typography.section, color: colors.text, fontSize: 18, lineHeight: 24, marginTop: spacing.md, marginBottom: 6 }, group: { overflow: 'hidden', borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface },
  row: { minHeight: 66, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingHorizontal: spacing.md, paddingVertical: 7 }, rowDivider: { borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, rowIcon: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 14, backgroundColor: colors.accentSoft }, iconWarning: { backgroundColor: '#FFF2DE' }, iconMuted: { backgroundColor: '#F0EBFA' }, rowCopy: { flex: 1, minWidth: 0 }, rowTitle: { ...typography.bodyStrong, color: colors.text }, rowDetail: { fontSize: 10, lineHeight: 15, color: colors.textSecondary, marginTop: 2 }, stateBadge: { paddingHorizontal: 9, paddingVertical: 4, borderRadius: radius.pill, backgroundColor: colors.successSoft }, stateWarning: { backgroundColor: '#FFF0D8' }, stateMuted: { paddingHorizontal: 9, paddingVertical: 4, borderRadius: radius.pill, backgroundColor: '#F0EFED' }, stateText: { fontSize: 9, fontWeight: '800', color: colors.primary }, stateTextWarning: { color: '#C56C00' }, stateTextMuted: { fontSize: 9, fontWeight: '800', color: colors.textMuted },
  boundaryCard: { minHeight: 76, flexDirection: 'row', borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, boundary: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, paddingHorizontal: 6 }, boundaryIcon: { width: 34, height: 34, alignItems: 'center', justifyContent: 'center', borderRadius: 13, backgroundColor: colors.accentSoft }, boundaryText: { fontSize: 9, lineHeight: 14, color: colors.text, fontWeight: '700' }, authorizedCard: { minHeight: 130, flexDirection: 'row', alignItems: 'center', gap: spacing.md, marginTop: spacing.xl, padding: spacing.lg, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, authorizedCopy: { flex: 1 }, authorizedTitle: { ...typography.bodyStrong, color: colors.text }, authorizedText: { ...typography.caption, color: colors.textSecondary, lineHeight: 18, marginTop: 3 }, linkButton: { paddingHorizontal: spacing.md, paddingVertical: 9, borderRadius: radius.pill, backgroundColor: colors.accentSoft }, linkButtonText: { fontSize: 10, fontWeight: '800', color: colors.primary }, primaryButton: { minHeight: 46, alignItems: 'center', justifyContent: 'center', marginTop: spacing.md, borderRadius: radius.pill, backgroundColor: colors.primary }, primaryButtonText: { ...typography.bodyStrong, color: '#FFFFFF' },
});
