import { CANONICAL_SCENARIOS } from '@lazy-armor/plan-schema/mobile';
import { Ionicons } from '@expo/vector-icons';
import { useQuery } from '@tanstack/react-query';
import { router } from 'expo-router';
import { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../../src/api';
import { useAuthStore } from '../../src/auth-store';
import { workspaceColors as colors, radius, spacing, typography } from '../../src/design';

interface PlanSearchRow { id: string; name: string | null; currentVersion: { name: string } | null }

export default function SearchAiPage() {
  const token = useAuthStore((store) => store.token);
  const [mode, setMode] = useState<'search' | 'ai'>('search');
  const [query, setQuery] = useState('');
  const plans = useQuery({ queryKey: ['search-plans', token], queryFn: () => api<PlanSearchRow[]>('/plans', token), enabled: Boolean(token && mode === 'search') });
  const needle = query.trim().toLocaleLowerCase('zh-CN');
  const matchingPlans = useMemo(() => needle ? (plans.data ?? []).filter((item) => `${item.name ?? ''} ${item.currentVersion?.name ?? ''}`.toLocaleLowerCase('zh-CN').includes(needle)).slice(0, 8) : [], [needle, plans.data]);
  const matchingScenarios = useMemo(() => needle ? CANONICAL_SCENARIOS.filter((item) => `${item.label} ${item.key}`.toLocaleLowerCase('zh-CN').includes(needle)).slice(0, 12) : [], [needle]);
  return <SafeAreaView edges={[]} style={styles.safeArea}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <Text style={styles.title}>搜索与万事问</Text>
    <View style={styles.modes}><Mode label="搜索" selected={mode === 'search'} onPress={() => setMode('search')} /><Mode label="问万事问" selected={mode === 'ai'} onPress={() => setMode('ai')} /></View>
    {mode === 'search' ? <><View style={styles.search}><Ionicons name="search-outline" size={19} color={colors.textMuted} /><TextInput value={query} onChangeText={setQuery} placeholder="搜索计划或场景" placeholderTextColor={colors.textMuted} style={styles.input} /></View><Text style={styles.boundary}>搜索词仅在设备内匹配已加载的本人计划与规范场景，不会发送给模型。执行记录、消息与统一权限索引仍待后端契约。</Text>{needle ? <><ResultSection title="我的计划" empty={matchingPlans.length === 0}>{matchingPlans.map((item) => <Result key={item.id} label={item.name ?? item.currentVersion?.name ?? '未命名计划'} onPress={() => router.push(`/plans/${item.id}` as never)} />)}</ResultSection><ResultSection title="相关场景" empty={matchingScenarios.length === 0}>{matchingScenarios.map((item) => <Result key={`${item.domain}.${item.key}`} label={item.label} onPress={() => router.push(`/domains/${item.domain}/${item.key}` as never)} />)}</ResultSection></> : null}</> : <View style={styles.aiUnavailable}><View style={styles.aiIcon}><Ionicons name="sparkles-outline" size={24} color={colors.primary} /></View><Text style={styles.cardTitle}>AI 暂不可用</Text><Text style={styles.body}>当前服务端 Agent 使用演示模型，尚未通过正式模型、权限隔离与敏感数据边界验收。本页不会调用它，也不会把演示输出冒充真实规划结果。</Text><Pressable accessibilityRole="button" onPress={() => setMode('search')} style={styles.backToSearch}><Text style={styles.backToSearchText}>继续使用搜索</Text></Pressable></View>}
  </ScrollView></SafeAreaView>;
}

function Mode({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable accessibilityRole="tab" accessibilityState={{ selected }} onPress={onPress} style={[styles.mode, selected && styles.modeSelected]}><Text style={[styles.modeText, selected && styles.modeTextSelected]}>{label}</Text></Pressable>; }
function ResultSection({ title, empty, children }: { title: string; empty: boolean; children: React.ReactNode }) { return <View style={styles.results}><Text style={styles.sectionTitle}>{title}</Text>{empty ? <Text style={styles.empty}>没有匹配结果</Text> : children}</View>; }
function Result({ label, onPress }: { label: string; onPress: () => void }) { return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.result, pressed && styles.pressed]}><Text style={styles.resultText}>{label}</Text><Ionicons name="chevron-forward" size={17} color={colors.textMuted} /></Pressable>; }
const styles = StyleSheet.create({ safeArea: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, paddingBottom: spacing.xxl }, title: { ...typography.title, color: colors.text, marginTop: spacing.md }, modes: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.lg }, mode: { minHeight: 44, justifyContent: 'center', paddingHorizontal: spacing.lg, borderRadius: radius.pill, backgroundColor: '#EFEEEA' }, modeSelected: { backgroundColor: colors.primary }, modeText: { ...typography.caption, color: colors.textSecondary, fontWeight: '800' }, modeTextSelected: { color: '#FFFFFF' }, search: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingHorizontal: spacing.md, marginTop: spacing.md, borderRadius: radius.pill, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, input: { ...typography.body, color: colors.text, flex: 1, paddingVertical: 0 }, boundary: { fontSize: 10, lineHeight: 16, color: colors.textMuted, marginTop: spacing.sm }, results: { marginTop: spacing.lg }, sectionTitle: { ...typography.section, color: colors.text, marginBottom: spacing.xs }, result: { minHeight: 48, flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border, backgroundColor: colors.surface }, resultText: { ...typography.body, color: colors.text, flex: 1 }, pressed: { backgroundColor: colors.pressed }, empty: { ...typography.caption, color: colors.textMuted, paddingVertical: spacing.md }, aiUnavailable: { alignItems: 'center', marginTop: spacing.xl, padding: spacing.xxl, borderRadius: radius.lg, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, aiIcon: { width: 52, height: 52, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.accentSoft }, cardTitle: { ...typography.cardTitle, color: colors.text, marginTop: spacing.lg }, body: { ...typography.body, color: colors.textSecondary, textAlign: 'center', lineHeight: 22, marginTop: spacing.sm }, backToSearch: { minHeight: 44, justifyContent: 'center', paddingHorizontal: spacing.lg, marginTop: spacing.lg, borderRadius: radius.pill, backgroundColor: colors.accentSoft }, backToSearchText: { ...typography.bodyStrong, color: colors.primary } });
