import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { Alert, Pressable, Text, View } from 'react-native';
import { Button, Card, EditorPage, Field, ui } from '../src/editor-ui';
import { api, resolveApiUrl } from '../src/api';
import { useAuthStore } from '../src/auth-store';
interface Config { source?: string | null; userConfigured?: boolean; provider: string; configured: boolean; maskedKey: string | null; model: string; thinkingMode: string; status: string }
export default function AiService() { const token = useAuthStore(s => s.token); const client = useQueryClient(); const config = useQuery({ queryKey: ['ai-service', token], queryFn: () => api<Config>('/ai-service', token), enabled: Boolean(token) }); const [model, setModel] = useState('deepseek-flash'); const [thinkingMode, setThinkingMode] = useState('AUTO'); const [key, setKey] = useState(''); const [editing, setEditing] = useState(false); const [error, setError] = useState(''); useEffect(() => { if (config.data) { setModel(config.data.model); setThinkingMode(config.data.thinkingMode); } }, [config.data]);
 const save = useMutation({ mutationFn: () => { if (key && !resolveApiUrl().startsWith('https://')) throw new Error('当前连接使用 HTTP。请连接 HTTPS 服务器后提交 API Key。'); return api<Config>('/ai-service', token, { method: 'PUT', body: JSON.stringify({ model, thinkingMode, ...(key ? { apiKey: key } : {}) }) }); }, onSuccess: async data => { setKey(''); setEditing(false); setError(''); client.setQueryData(['ai-service', token], data); await client.invalidateQueries({ queryKey: ['ai-service', token] }); }, onError: e => setError(e.message) });
 const test = useMutation({ mutationFn: () => api<Config>('/ai-service/test', token, { method: 'POST' }), onSuccess: data => { setError(''); client.setQueryData(['ai-service', token], data); }, onError: e => setError(e.message) });
 const remove = useMutation({ mutationFn: () => api('/ai-service', token, { method: 'DELETE' }), onSuccess: async () => { setKey(''); await client.invalidateQueries({ queryKey: ['ai-service', token] }); }, onError: e => setError(e.message) });
 const secureTransport = resolveApiUrl().startsWith('https://');
 const busy = save.isPending || test.isPending || remove.isPending;
 return <EditorPage title="AI 服务"><Card><View style={ui.row}><Text style={[ui.label, { flex: 1 }]}>模型服务</Text><Text style={ui.label}>DeepSeek</Text></View><Text style={ui.label}>API Key</Text>{editing || !config.data?.userConfigured ? secureTransport ? <Field label="DeepSeek API Key" value={key} onChange={setKey} max={256} placeholder="输入 API Key（仅通过 HTTPS 提交）" secret /> : <Text style={ui.detail}>当前开发连接未启用 HTTPS，API Key 提交已禁用。</Text> : <View style={ui.line}><Text style={[ui.detail, { flex: 1 }]}>{config.data.maskedKey}</Text><Pressable disabled={!secureTransport} onPress={() => setEditing(true)}><Text style={{ color: '#287BFF' }}>修改</Text></Pressable></View>}<Text style={ui.label}>模型</Text>{[{ value: 'deepseek-flash', title: 'DeepSeek Flash', detail: '推荐 · 日常会话和计划' }, { value: 'deepseek-v4-pro', title: 'DeepSeek V4 Pro', detail: '复杂分析与规划' }].map(item => <Pressable key={item.value} style={ui.row} onPress={() => setModel(item.value)}><Text style={{ color: '#287BFF' }}>{model === item.value ? '●' : '○'}</Text><View style={{ flex: 1 }}><Text style={ui.label}>{item.title}</Text><Text style={ui.detail}>{item.detail}</Text></View></Pressable>)}<Text style={ui.label}>思考模式</Text><View style={ui.line}>{[{ value: 'AUTO', label: '智能' }, { value: 'FAST', label: '快速' }, { value: 'DEEP', label: '深度' }].map(item => <Pressable key={item.value} style={[ui.pill, thinkingMode === item.value && { backgroundColor: '#BDD9FF' }]} onPress={() => setThinkingMode(item.value)}><Text>{item.label}</Text></Pressable>)}</View><Text style={ui.label}>状态</Text><Text style={ui.detail}>● {config.data?.status ?? (config.isError ? '读取失败' : '读取中')}</Text><Button secondary label={test.isPending ? '测试中…' : '测试连接'} disabled={busy || !config.data?.configured || Boolean(key)} onPress={() => test.mutate()} /></Card><Card title="使用说明"><Text style={ui.detail}>AI 只会获取当前会话或计划所需的数据。涉及真实操作仍需经过权限、风险和确认流程。</Text></Card>{error ? <Text style={ui.error}>{error}</Text> : null}<Button label={save.isPending ? '保存中…' : '保存'} disabled={busy || (!config.data?.userConfigured && !key) || (Boolean(key) && !secureTransport)} onPress={() => save.mutate()} />{config.data?.userConfigured ? <Button secondary label="删除配置" disabled={busy} onPress={() => Alert.alert('删除 AI 配置？', '密钥将撤销，会话与计划记录保留。', [{ text: '取消' }, { text: '删除', style: 'destructive', onPress: () => remove.mutate() }])} /> : null}<Button secondary label="返回继续" onPress={() => router.canGoBack() ? router.back() : router.replace('/chat' as never)} /></EditorPage>;
}
