import { Ionicons } from '@expo/vector-icons';
import { useQuery } from '@tanstack/react-query';
import { router } from 'expo-router';
import { ActivityIndicator, Pressable, Text, View } from 'react-native';
import { api } from '../src/api';
import { useAuthStore } from '../src/auth-store';
import { deviceInstallationId } from '../src/device-installation-id';
import { useRuntimeSettings } from '../src/runtime-settings';
import { Button, Card, EditorPage, ui } from '../src/editor-ui';
interface Device { id: string; deviceId: string; status: string; online: boolean; onlineState: string; lastProvedAt: string }
export default function ConnectedDevices() { const token = useAuthStore(s => s.token); const name = useRuntimeSettings(s => s.deviceName); const local = useQuery({ queryKey: ['local-installation-id'], queryFn: deviceInstallationId }); const devices = useQuery({ queryKey: ['trusted-devices', token], queryFn: () => api<Device[]>('/trusted-devices', token), enabled: Boolean(token), refetchInterval: 30000 }); const active = (devices.data ?? []).filter(device => device.status === 'active'); return <EditorPage title="设备"><Text style={[ui.title, { fontSize: 25, marginTop: 16 }]}>已连接设备</Text><Text style={ui.detail}>查看本账号已完成认证的设备</Text>{!token ? <Button label="登录后查看设备" onPress={() => router.push('/auth/login' as never)} /> : devices.isLoading ? <ActivityIndicator color="#3083FF" /> : devices.isError ? <Button secondary label="读取失败，点击重试" onPress={() => void devices.refetch()} /> : active.length ? active.map(device => { const isLocal = device.deviceId === local.data; return <Pressable key={device.id} style={[ui.card, { paddingVertical: 24 }]} onPress={() => router.push(`/devices/${device.id}` as never)}><View style={ui.line}><View style={[ui.icon, { width: 56, height: 64, backgroundColor: '#EAE3FF' }]}><Ionicons name="phone-portrait" size={38} color="#7255D9" /></View><View style={{ flex: 1 }}><Text style={ui.title}>{isLocal ? name ?? '当前手机' : `已认证设备 · ${device.deviceId.slice(-6)}`}</Text><Text style={[ui.detail, { marginTop: 6 }]}><Text style={{ color: device.online ? '#14B979' : '#8996AC' }}>● </Text>{isLocal ? '本机 · ' : ''}{device.online ? '当前在线' : '当前离线'} · 已认证</Text></View><Ionicons name="chevron-forward" size={24} color="#61718C" /></View></Pressable>; }) : <Card><Text style={ui.detail}>还没有已认证设备。连接本机应用并完成认证后会显示在这里。</Text></Card>}<Text style={[ui.title, { marginTop: 20 }]}>连接更多设备</Text><Pressable style={ui.card} onPress={() => router.push('/connections/add' as never)}><View style={ui.line}><View style={ui.icon}><Ionicons name="phone-portrait-outline" size={28} color="#7255D9" /></View><Text style={[ui.title, { flex: 1 }]}>连接当前安卓手机</Text><Ionicons name="chevron-forward" size={22} color="#61718C" /></View></Pressable>{[{ name: 'Mac', icon: 'laptop-outline' as const }, { name: '浏览器插件', icon: 'globe-outline' as const }, { name: 'iPhone', icon: 'phone-portrait-outline' as const }].map(item => <View key={item.name} style={[ui.card, { opacity: 0.7 }]}><View style={ui.line}><View style={ui.icon}><Ionicons name={item.icon} size={28} color="#7255D9" /></View><Text style={[ui.title, { flex: 1 }]}>连接你的{item.name}</Text><Text style={ui.detail}>暂未开放</Text></View></View>)}</EditorPage>; }
