import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { router, useLocalSearchParams } from 'expo-router';
import { Alert, Switch, Text, View } from 'react-native';
import type { ResourceProjection } from '@lazy-armor/plan-schema';
import { api } from '../src/api';
import { useAuthStore } from '../src/auth-store';
import { Button, Card, EditorPage, ui } from '../src/editor-ui';
import { ErrorState, LoadingState } from '../src/consumer-ui';
import { ConnectionCapabilityPanel } from '../src/connection-capability-panel';
import { ConsumerPresentationMapper as presentation } from '../src/consumer-presentation';
export default function ResourceDetail(){
 const {id}=useLocalSearchParams<{id:string}>();const token=useAuthStore(s=>s.token);const client=useQueryClient();
 const resource=useQuery({queryKey:['resources',token],queryFn:()=>api<ResourceProjection[]>('/consumer/resources',token),enabled:Boolean(token)});
 const permissions=useQuery({queryKey:['resource-permissions',token,id],queryFn:()=>api<Array<{capability:string;name:string;granted:boolean}>>(`/connections/${id}/permissions`,token),enabled:Boolean(token&&id)});
 const plans=useQuery({queryKey:['resource-plans',token,id],queryFn:()=>api<Array<{planId:string;planName:string}>>(`/connections/${id}/plans`,token),enabled:Boolean(token&&id)});
 const item=resource.data?.find(row=>row.sourceRef.type==='Connection'&&row.sourceRef.id===id);
 const refresh=async()=>{await Promise.all([permissions.refetch(),resource.refetch(),client.invalidateQueries({queryKey:['connection-capabilities',token,id]}),client.invalidateQueries({queryKey:['resource-workspace',token]})]);};
 const update=useMutation({mutationFn:(permission:{capability:string;granted:boolean})=>api(`/connections/${id}/permissions`,token,{method:'PUT',body:JSON.stringify({permissions:[{capability:permission.capability,granted:!permission.granted}]})}),onSuccess:refresh});
 const validate=useMutation({mutationFn:()=>api(`/connections/${id}/validate`,token,{method:'POST'}),onSuccess:refresh});
 const disconnect=useMutation({mutationFn:()=>api(`/connections/${id}`,token,{method:'DELETE'}),onSuccess:async()=>{await Promise.all([client.invalidateQueries({queryKey:['resources']}),client.invalidateQueries({queryKey:['resource-workspace',token]}),client.invalidateQueries({queryKey:['connection-capabilities',token,id]})]);router.replace('/resources' as never);}});
 return <EditorPage title="资源详情">{resource.isLoading?<LoadingState/>:resource.isError?<ErrorState onRetry={()=>void resource.refetch()}/>:!item?<Text style={ui.detail}>未找到此资源，请返回资源页刷新。</Text>:<><Card title={presentation.text(item.name,'资源')}><Text style={ui.detail}>{presentation.text(item.summary)}</Text><Text style={ui.detail}>{item.status}</Text><Text style={ui.detail}>配置：已保存连接配置</Text><Text style={ui.detail}>授权：{permissions.data?.some(p=>p.granted)?'已授权（逐项检查）':'需要授权'}</Text><Text style={ui.detail}>健康：{item.health==='VERIFIED'?'正常（当前读取检查）':'待检查'}</Text><Text style={ui.detail}>最近检查：{item.lastVerifiedAt?presentation.dateTime(item.lastVerifiedAt):'暂无'}</Text>{item.reasons.map(reason=><Text key={reason} style={ui.detail}>{presentation.reason(reason)}</Text>)}</Card><ConnectionCapabilityPanel id={id} token={token}/><Button secondary label={validate.isPending?"检查中…":"检查连接"} disabled={validate.isPending||update.isPending} onPress={()=>validate.mutate()}/><Card title="数据权限">{permissions.isLoading?<LoadingState/>:permissions.isError?<ErrorState onRetry={()=>void permissions.refetch()}/>:permissions.data?.map(permission=><View key={permission.capability} style={ui.line}><Text style={[ui.label,{flex:1}]}>{presentation.text(permission.name,'数据读取权限')}</Text><Switch value={permission.granted} disabled={update.isPending} onValueChange={()=>{if(permission.granted)Alert.alert('关闭数据权限？','相关计划可能需要重新补充资源。',[{text:'取消'},{text:'关闭',onPress:()=>update.mutate(permission)}]);else update.mutate(permission);}}/></View>)}</Card><Card title="关联计划">{plans.isError?<ErrorState onRetry={()=>void plans.refetch()}/>:plans.isLoading?<LoadingState/>:plans.data?.length?plans.data.map(plan=><Button key={plan.planId} secondary label={presentation.text(plan.planName,'查看计划')} onPress={()=>router.push(`/plans/${plan.planId}` as never)}/>):<Text style={ui.detail}>暂未用于计划</Text>}</Card><Button secondary label="断开资源" disabled={disconnect.isPending} onPress={()=>Alert.alert('断开资源？','计划与历史会保留，相关任务将重新检查资源。',[{text:'取消'},{text:'断开',style:'destructive',onPress:()=>disconnect.mutate()}])}/>{update.isError||disconnect.isError||validate.isError?<Text style={ui.error}>{presentation.error(update.error??disconnect.error??validate.error)}</Text>:null}</>}</EditorPage>;
}
