import {canonicalServiceDeliveryMode,serviceDeliveryLabels,servicePriceText} from '@lazy-armor/plan-schema/service-offering';
import { useQuery } from '@tanstack/react-query';
import { router, useLocalSearchParams } from 'expo-router';
import { ActivityIndicator, Image, Text } from 'react-native';
import { Button, Card, EditorPage, ui } from '../src/editor-ui';
import { api, resolveApiUrl } from '../src/api';
import { useAuthStore } from '../src/auth-store';
interface Offering { id: string; title: string; summary: string; deliveryMode:string;priceMode:string;serviceType:string;domain:string;serviceAddress:string|null;locationInstructions:string|null;remoteInstructions:string|null;shippingInstructions:string|null;shippingFeeRules:string|null;deliveryInstructions:string|null;bookingInstructions:string|null; tags: string[]; provider: { displayName: string; verified: boolean }; priceMinMinor: number | null; priceMaxMinor: number | null; currency: string | null; serviceArea: string | null; contact: string | null; imageUrl: string | null }
export default function ServiceDetail() { const { id } = useLocalSearchParams<{ id: string }>(); const token = useAuthStore(s => s.token); const query = useQuery({ queryKey: ['service-offerings', token], queryFn: () => api<Offering[]>('/service-offerings', token), enabled: Boolean(token) }); const item = query.data?.find(s => s.id === id); return <EditorPage title="服务详情">{query.isLoading ? <ActivityIndicator color="#3083FF" /> : query.isError ? <Button secondary label="读取失败，点击重试" onPress={() => void query.refetch()} /> : !item ? <Card><Text style={ui.detail}>该服务暂不可用或已下架</Text></Card> : <><Card icon="storefront" title={item.title}><Text style={ui.detail}>{item.summary}</Text>{item.imageUrl ? <Image source={{ uri: item.imageUrl.startsWith('/api/') ? resolveApiUrl() + item.imageUrl : item.imageUrl }} style={{ width: '100%', height: 180, borderRadius: 16 }} resizeMode="cover" /> : null}<Text style={ui.pill}>{serviceDeliveryLabels[canonicalServiceDeliveryMode(item.deliveryMode)!]??'服务方式待确认'}</Text><Text style={ui.detail}>{item.tags.join(' · ')}</Text></Card><Card title="服务提供方"><Text style={ui.label}>{item.provider.displayName}{item.provider.verified ? ' · 已认证' : ''}</Text></Card><Card title="交付与联系"><Text style={ui.detail}>{item.serviceType==='USER_SERVICE'?'服务类型待补充':item.serviceType}</Text>
{['ONSITE','LOGISTICS'].includes(item.deliveryMode)&&item.serviceArea?<Text style={ui.detail}>覆盖区域：{item.serviceArea}</Text>:null}
{item.deliveryMode==='AT_LOCATION'?<><Text style={ui.detail}>服务地址：{item.serviceAddress}</Text>{item.locationInstructions?<Text style={ui.detail}>{item.locationInstructions}</Text>:null}</>:null}
{item.deliveryMode==='REMOTE'?<Text style={ui.detail}>线上交付：{item.remoteInstructions}</Text>:null}
{item.deliveryMode==='LOGISTICS'?<><Text style={ui.detail}>寄送说明：{item.shippingInstructions}</Text><Text style={ui.detail}>运费规则：{item.shippingFeeRules}</Text></>:null}
{item.deliveryMode==='OTHER'?<Text style={ui.detail}>{item.deliveryInstructions}</Text>:null}
{item.bookingInstructions?<Text style={ui.detail}>预约说明：{item.bookingInstructions}</Text>:null}<Text selectable style={ui.detail}>{item.contact ?? '预约时与服务提供方联系'}</Text></Card><Card title="服务费用"><Text style={ui.label}>{servicePriceText(item)}</Text></Card><Button label="预约此服务" onPress={() => router.push(`/request-service?offeringId=${item.id}` as never)} /><Button label="围绕此服务创建计划" onPress={() => router.push({ pathname: '/chat', params: { mode: 'plan', serviceOfferingId: item.id } } as never)} /></>}</EditorPage>; }

