import { SegmentedControl } from '../src/consumer-ui';
import { ConsumerPresentationMapper as presentation } from '../src/consumer-presentation';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, Alert, Text } from 'react-native';
import { api } from '../src/api';
import { useAuthStore } from '../src/auth-store';
import { Button, Card, EditorPage, ui } from '../src/editor-ui';
interface RequestRow { request: { id: string; offeringId:string; status: string; scheduledAt: string; requirement: string; address: string; version: number }; offering: { title: string }; nextAction: { label: string; status: string } | null }
export default function ServiceRequests() {
 const { id,role,offeringId } = useLocalSearchParams<{ id?: string;role?: string;offeringId?: string }>(); const [filter,setFilter]=useState('all'); const token = useAuthStore(s => s.token); const client = useQueryClient(); const [error, setError] = useState(''); const [pending, setPending] = useState(false);
 const query = useQuery({ queryKey: ['service-requests', token,role], queryFn: () => api<RequestRow[]>(`/service-requests${role==='provider'||role==='consumer'?'?role='+role:''}`, token), enabled: Boolean(token), refetchInterval: 15000 });
 async function cancel(item: RequestRow, status = 'CANCELLED') { setPending(true); try { await api(`/service-requests/${item.request.id}/status`, token, { method: 'POST', body: JSON.stringify({ status, version: item.request.version }) }); await query.refetch(); await Promise.all([client.invalidateQueries({ queryKey: ['timeline'] }), client.invalidateQueries({ queryKey: ['work-items'] }), client.invalidateQueries({ queryKey: ['my-service-offerings'] })]); } catch (e) { setError(e instanceof Error ? e.message : '取消失败'); } finally { setPending(false); } }
 const rows = (query.data ?? []).filter(item => (!id || item.request.id === id) && (!offeringId || item.request.offeringId === offeringId) && (filter==='all'||filter==='pending'&&item.request.status==='PENDING'||filter==='active'&&['BOOKED','IN_PROGRESS'].includes(item.request.status)||filter==='done'&&item.request.status==='COMPLETED'));
 return <EditorPage title={role==='provider'?'收到的请求':'我的服务'}>{!id?<SegmentedControl value={filter} options={[{value:'all',label:'全部'},{value:'pending',label:'待处理'},{value:'active',label:'进行中'},{value:'done',label:'已完成'}]} onChange={setFilter}/>:null}{error ? <Text style={ui.error}>{presentation.error(error)}</Text> : null}{query.isLoading ? <ActivityIndicator /> : query.isError ? <Button label="读取失败，重试" onPress={() => void query.refetch()} /> : rows.map(item => <Card key={item.request.id} title={item.offering.title}><Text style={ui.label}>{({ PENDING: '待确认', BOOKED: '已预约', IN_PROGRESS: '进行中', COMPLETED: '已完成', CANCELLED: '已取消' } as Record<string, string>)[item.request.status] ?? '待处理'}</Text><Text style={ui.detail}>{presentation.dateTime(item.request.scheduledAt)}</Text><Text style={ui.detail}>{item.request.address}</Text><Text style={ui.detail}>{item.request.requirement}</Text>{item.nextAction ? <Button label={item.nextAction.label} disabled={pending} onPress={() => Alert.alert(item.nextAction!.label + '？', '确认后进度将同步到日程。', [{ text: '取消' }, { text: '确认', onPress: () => void cancel(item, item.nextAction!.status) }])} /> : null}{!['COMPLETED', 'CANCELLED'].includes(item.request.status) ? <Button secondary label={role==='provider'&&item.request.status==='PENDING'?'拒绝请求':'取消预约'} disabled={pending} onPress={() => Alert.alert('取消预约？', '取消后服务提供方将不再继续此请求。', [{ text: '保留' }, { text: '取消预约', onPress: () => void cancel(item) }])} /> : null}</Card>)}{!query.isLoading && !query.isError && !rows.length ? <Text style={ui.detail}>暂无服务请求</Text> : null}</EditorPage>;
}
