import { useQuery } from '@tanstack/react-query';
import { router, useLocalSearchParams } from 'expo-router';
import { ActivityIndicator, Image, Text } from 'react-native';
import { Button, Card, EditorPage, ui } from '../src/editor-ui';
import { api, resolveApiUrl } from '../src/api';
import { useAuthStore } from '../src/auth-store';
interface Offering { id: string; title: string; summary: string; deliveryMode: string; tags: string[]; provider: { displayName: string; verified: boolean }; priceMinMinor: number | null; priceMaxMinor: number | null; currency: string | null; serviceArea: string | null; contact: string | null; imageUrl: string | null }
export default function ServiceDetail() { const { id } = useLocalSearchParams<{ id: string }>(); const token = useAuthStore(s => s.token); const query = useQuery({ queryKey: ['service-offerings', token], queryFn: () => api<Offering[]>('/service-offerings', token), enabled: Boolean(token) }); const item = query.data?.find(s => s.id === id); return <EditorPage title="服务详情">{query.isLoading ? <ActivityIndicator color="#3083FF" /> : query.isError ? <Button secondary label="读取失败，点击重试" onPress={() => void query.refetch()} /> : !item ? <Card><Text style={ui.detail}>该服务暂不可用或已下架</Text></Card> : <><Card icon="storefront" title={item.title}><Text style={ui.detail}>{item.summary}</Text>{item.imageUrl ? <Image source={{ uri: item.imageUrl.startsWith('/api/') ? resolveApiUrl() + item.imageUrl : item.imageUrl }} style={{ width: '100%', height: 180, borderRadius: 16 }} resizeMode="cover" /> : null}<Text style={ui.pill}>{item.deliveryMode === 'LOCAL' ? '上门服务' : '远程服务'}</Text><Text style={ui.detail}>{item.tags.join(' · ')}</Text></Card><Card title="服务提供方"><Text style={ui.label}>{item.provider.displayName}{item.provider.verified ? ' · 已认证' : ''}</Text></Card><Card title="服务范围与联系"><Text style={ui.detail}>{item.serviceArea ?? '请与服务提供方确认范围'}</Text><Text selectable style={ui.detail}>{item.contact ?? '预约时与服务提供方联系'}</Text></Card><Card title="服务费用"><Text style={ui.label}>{item.priceMinMinor === null ? '费用请与服务提供方确认' : `${item.currency ?? 'CNY'} ${(item.priceMinMinor / 100).toFixed(2)}${item.priceMaxMinor !== null && item.priceMaxMinor !== item.priceMinMinor ? ` – ${(item.priceMaxMinor / 100).toFixed(2)}` : ''}`}</Text></Card><Button label="预约此服务" onPress={() => router.push(`/request-service?offeringId=${item.id}` as never)} /><Button label="围绕此服务创建计划" onPress={() => router.push({ pathname: '/chat', params: { mode: 'plan', serviceOfferingId: item.id } } as never)} /></>}</EditorPage>; }

