import { useEffect, useState } from 'react';
import { Modal, Pressable, Text, View } from 'react-native';
import { ConsumerPresentationMapper as p } from './consumer-presentation';
import { ui } from './editor-ui';
export function CalendarSheet({visible,date,onSelect,onClose}:{visible:boolean;date:string;onSelect:(date:string)=>void;onClose:()=>void}) {
 const [month,setMonth]=useState(()=>new Date(`${date}T12:00:00`));
 useEffect(()=>{if(visible)setMonth(new Date(`${date}T12:00:00`));},[visible,date]);
 const first=new Date(month.getFullYear(),month.getMonth(),1);const days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();
 return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={{flex:1,justifyContent:'flex-end',backgroundColor:'rgba(16,24,40,0.28)'}}><View style={[ui.card,{padding:22,paddingBottom:35}]}><View style={[ui.line,{justifyContent:'space-between'}]}><Pressable accessibilityLabel="上个月" style={ui.back} onPress={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><Text style={ui.title}>‹</Text></Pressable><Text style={ui.title}>{month.getFullYear()}年 {month.getMonth()+1}月</Text><Pressable accessibilityLabel="下个月" style={ui.back} onPress={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><Text style={ui.title}>›</Text></Pressable></View><View style={{flexDirection:'row'}}>{['日','一','二','三','四','五','六'].map(day=><Text key={day} style={[ui.detail,{width:'14.28%',textAlign:'center'}]}>{day}</Text>)}</View><View style={{flexDirection:'row',flexWrap:'wrap'}}>{Array.from({length:first.getDay()+days},(_,index)=>{const day=index-first.getDay()+1;if(day<1)return <View key={index} style={{width:'14.28%',height:44}}/>;const value=p.localDate(new Date(month.getFullYear(),month.getMonth(),day));return <Pressable key={index} accessibilityLabel={value} accessibilityState={{selected:value===date}} onPress={()=>{onSelect(value);onClose();}} style={({pressed})=>({width:'14.28%',height:44,alignItems:'center',justifyContent:'center',borderRadius:22,backgroundColor:value===date?'#2589FF':pressed?'#D9E8F8':'transparent'})}><Text style={{color:value===date?'white':'#101828',fontSize:16}}>{day}</Text></Pressable>;})}</View><View style={[ui.line,{justifyContent:'space-between'}]}><Pressable style={ui.back} onPress={()=>{onSelect(p.localDate());onClose();}}><Text style={{color:'#2589FF'}}>今天</Text></Pressable><Pressable accessibilityLabel="关闭日历" style={ui.back} onPress={onClose}><Text style={ui.label}>关闭</Text></Pressable></View></View></View></Modal>;
}
