import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import type { ReactNode } from 'react';
export const consumerTokens = {text:'#101828',secondary:'#667085',muted:'#98A2B3',primary:'#2589FF',card:'rgba(255,255,255,0.38)',border:'rgba(255,255,255,0.18)',pressed:'rgba(211,227,247,0.42)'};
export const drawerTokens = { width: '80%' as const, maxWidth: 340, item: { fontSize: 14, fontWeight: '600' as const, color: consumerTokens.text }, background: '#FFFFFF', card: '#F4F6F9', title: { fontSize: 16, fontWeight: '700' as const, color: consumerTokens.text }, body: { fontSize: 14, lineHeight: 20, color: consumerTokens.secondary } };
export function SegmentedControl<T extends string>({value,options,onChange,variant='default'}:{variant?:'default'|'drawer';value:T;options:ReadonlyArray<{value:T;label:string;count?:number}>;onChange:(value:T)=>void}) {
 return <View style={[styles.segment,variant==='drawer'&&{backgroundColor:'#EEF1F5'}]}>{options.map(option=><Pressable key={option.value} accessibilityRole="tab" accessibilityLabel={option.label} accessibilityState={{selected:value===option.value}} onPress={()=>onChange(option.value)} style={({pressed})=>[styles.segmentItem,value===option.value&&styles.selected,variant==='drawer'&&value===option.value&&{backgroundColor:'#D5E2F3'},pressed&&styles.pressed]}><Text numberOfLines={1} style={[styles.segmentText,value===option.value&&styles.selectedText,variant==='drawer'&&value===option.value&&{color:'#174D91'}]}>{option.label}{option.count===undefined?'':` ${option.count}`}</Text></Pressable>)}</View>;
}
export function ChipTabs({value,options,onChange}:{value:string;options:ReadonlyArray<{value:string;label:string}>;onChange:(value:string)=>void}) { return <ScrollView horizontal style={{flexGrow:0,flexShrink:0,height:42}} showsHorizontalScrollIndicator={false} contentContainerStyle={[styles.chips,{alignItems:'center'}]}>{options.map(option=><Pressable key={option.value} accessibilityRole="tab" accessibilityState={{selected:value===option.value}} onPress={()=>onChange(option.value)} style={({pressed})=>[styles.chip,value===option.value&&styles.selected,pressed&&styles.pressed]}><Text style={[styles.segmentText,value===option.value&&styles.selectedText]}>{option.label}</Text></Pressable>)}</ScrollView>; }
export function StatusBadge({label}:{label:string}) {return <View style={styles.badge}><Text style={styles.badgeText}>{label}</Text></View>;}
export function EmptyState({title,detail,action,onPress}:{title:string;detail?:string;action?:string;onPress?:()=>void}) {return <View style={styles.card}><Text style={styles.title}>{title}</Text>{detail?<Text style={styles.detail}>{detail}</Text>:null}{action&&onPress?<Pressable accessibilityRole="button" style={styles.action} onPress={onPress}><Text style={styles.selectedText}>{action}</Text></Pressable>:null}</View>;}
export function LoadingState(){return <View accessibilityLabel="正在读取" style={{gap:6}}>{[0,1,2].map(index=><View key={index} style={[styles.card,{minHeight:60}]}><View style={{height:16,width:'52%',borderRadius:8,backgroundColor:'rgba(150,170,192,0.24)'}}/><View style={{height:12,width:'82%',borderRadius:6,backgroundColor:'rgba(150,170,192,0.16)'}}/></View>)}<View style={styles.loading}><ActivityIndicator color={consumerTokens.primary}/><Text style={styles.detail}>正在读取…</Text></View></View>;}
export function ErrorState({onRetry,detail='暂时无法读取，请稍后重试'}:{onRetry:()=>void;detail?:string}) {return <EmptyState title="暂时无法读取" detail={detail} action="重试" onPress={onRetry}/>;}
export function ConsumerCard({children}:{children:ReactNode}){return <View style={styles.card}>{children}</View>;}
const styles=StyleSheet.create({segment:{height:44,padding:6,borderRadius:12,flexDirection:'row',backgroundColor:'rgba(210,224,240,0.22)',gap:3},segmentItem:{flex:1,borderRadius:8,alignItems:'center',justifyContent:'center',minWidth:0},selected:{backgroundColor:'rgba(255,255,255,0.44)'},segmentText:{fontSize:14,color:consumerTokens.secondary,fontWeight:'500'},selectedText:{color:consumerTokens.primary,fontWeight:'700'},pressed:{backgroundColor:consumerTokens.pressed},chips:{gap:5,paddingVertical:3},chip:{minHeight:36,justifyContent:'center',paddingHorizontal:11,borderRadius:9,backgroundColor:'rgba(255,255,255,0.22)'},badge:{alignSelf:'flex-start',borderRadius:10,paddingHorizontal:8,paddingVertical:3,backgroundColor:'rgba(225,237,252,0.4)'},badgeText:{fontSize:12,color:consumerTokens.primary},card:{padding:10,gap:5,borderRadius:10,backgroundColor:consumerTokens.card,borderWidth:StyleSheet.hairlineWidth,borderColor:consumerTokens.border},title:{fontSize:14,fontWeight:'700',color:consumerTokens.text},detail:{fontSize:12,lineHeight:18,color:consumerTokens.secondary},action:{minHeight:44,justifyContent:'center'},loading:{padding:24,gap:10,alignItems:'center'}});
