import { consumerTokens } from './consumer-ui';
import { Ionicons } from '@expo/vector-icons';
import { router, Stack } from 'expo-router';
import type { ComponentProps, ReactNode } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
export function EditorPage({ title, children, action }: { title: string; children: ReactNode; action?: ReactNode }) { return <SafeAreaView style={{ flex: 1 }}><Stack.Screen options={{ headerShown: false }} /><View style={ui.header}><Pressable accessibilityLabel="返回" onPress={() => router.canGoBack() ? router.back() : router.replace('/' as never)} style={ui.back}><Ionicons name="chevron-back" size={26} color="#172033" /></Pressable><Text style={ui.pageTitle}>{title}</Text><View style={ui.back}>{action}</View></View><KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={ui.content}>{children}</ScrollView></KeyboardAvoidingView></SafeAreaView>; }
export function Card({ title, detail, icon, children }: { title?: string; detail?: string; icon?: ComponentProps<typeof Ionicons>['name']; children: ReactNode }) { return <View style={ui.card}>{title ? <View style={ui.line}>{icon ? <View style={ui.icon}><Ionicons name={icon} size={25} color="#397AFF" /></View> : null}<View style={{ flex: 1 }}><Text style={ui.title}>{title}</Text>{detail ? <Text style={ui.detail}>{detail}</Text> : null}</View></View> : null}{children}</View>; }
export function Field({ label, value, onChange, max = 200, multiline = false, placeholder, secret = false }: { label?: string; value: string; onChange: (value: string) => void; max?: number; multiline?: boolean; placeholder?: string; secret?: boolean }) { return <View style={{ gap: 5 }}>{label ? <Text style={ui.label}>{label}</Text> : null}<TextInput secureTextEntry={secret} autoCorrect={!secret} autoCapitalize={secret ? 'none' : 'sentences'} accessibilityLabel={label ?? placeholder} value={value} onChangeText={onChange} maxLength={max} multiline={multiline} placeholder={placeholder} placeholderTextColor="#8996AA" style={[ui.input, multiline && { minHeight: 92, textAlignVertical: 'top' }]} /><Text style={ui.count}>{value.length}/{max}</Text></View>; }
export function Button({ label, onPress, secondary = false, disabled = false }: { label: string; onPress: () => void; secondary?: boolean; disabled?: boolean }) { return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[ui.button, secondary && ui.secondary, disabled && { opacity: 0.5 }]}><Text style={[ui.buttonText, secondary && { color: '#287BFF' }]}>{label}</Text></Pressable>; }
export const ui = StyleSheet.create({ header: { height: 56, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12 }, back: { width: 48, alignItems: 'center', justifyContent: 'center', minHeight: 44 }, pageTitle: { flex: 1, textAlign: 'center', color: consumerTokens.text, fontSize: 20, fontWeight: '700' }, content: { padding: 12, paddingBottom: 24, gap: 6, width: '100%', maxWidth: 600, alignSelf: 'center' }, card: { padding: 10, borderRadius: 10, backgroundColor: consumerTokens.card, gap: 6, minWidth: 0 }, line: { flexDirection: 'row', gap: 8, alignItems: 'center' }, icon: { width: 32, height: 32, borderRadius: 9, backgroundColor: 'rgba(234,241,255,0.38)', alignItems: 'center', justifyContent: 'center' }, title: { fontSize: 14, fontWeight: '700', color: consumerTokens.text }, label: { fontSize: 15, fontWeight: '600', color: consumerTokens.text }, detail: { fontSize: 13, color: consumerTokens.secondary, lineHeight: 18 }, input: { borderWidth: 1, borderColor: 'rgba(100,120,150,0.18)', borderRadius: 8, backgroundColor: 'rgba(248,251,255,0.32)', padding: 8, fontSize: 15, color: consumerTokens.text }, count: { textAlign: 'right', color: '#7384A0', fontSize: 12 }, button: { backgroundColor: '#3083FF', borderRadius: 9, minHeight: 44, alignItems: 'center', justifyContent: 'center' }, secondary: { backgroundColor: 'rgba(229,240,255,0.4)', minHeight: 40 }, buttonText: { color: '#FFF', fontSize: 14, fontWeight: '600' }, listRow: { paddingVertical: 7, gap: 4, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: 'rgba(100,120,150,0.24)' }, row: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#E2E9F4', paddingVertical: 8 }, pill: { borderRadius: 8, backgroundColor: 'rgba(231,240,255,0.32)', paddingHorizontal: 10, paddingVertical: 5 }, error: { color: '#D34050', fontSize: 13 } });

