import { Ionicons } from '@expo/vector-icons';
import { useQuery } from '@tanstack/react-query';
import { router } from 'expo-router';
import { useState } from 'react';
import { Modal, Pressable, ScrollView, Text, View } from 'react-native';
import { api } from './api';
import { useAuthStore } from './auth-store';
import { Button, ui } from './editor-ui';
interface Connection { id: string; connectorId: string; connectorName: string; status: string }
const catalog = [ { name: '日历', icon: 'calendar' as const, description: '读取日程事件', match: /calendar|日历/i }, { name: '通知', icon: 'notifications' as const, description: '发现重要消息', match: /notification|通知/i }, { name: '待办', icon: 'list' as const, description: '读取未完成事项', match: /todo|task|待办/i }, { name: '文件', icon: 'document' as const, description: '读取关联资料', match: /file|drive|文件/i } ];
export function PlanResources({ selected, onChange, summary = false }: { selected: string[]; onChange?: (resources: string[]) => void; summary?: boolean }) { const token = useAuthStore(s => s.token); const connections = useQuery({ queryKey: ['resources-connections', token], queryFn: () => api<Connection[]>('/connections', token), enabled: Boolean(token) }); const [open, setOpen] = useState(false); const [pending, setPending] = useState<string[]>([]); const options = [...catalog, ...(connections.data ?? []).filter(connection => !catalog.some(item => item.match.test(connection.connectorId + ' ' + connection.connectorName))).map(connection => ({ name: connection.connectorName, icon: 'link' as const, description: '已添加的应用或平台', match: new RegExp('^' + connection.connectorId.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '$') }))];
 const find = (name: string) => options.find(item => item.name === name); const connectionFor = (name: string) => { const resource = find(name); return resource && (connections.data ?? []).find(connection => resource.match.test(connection.connectorId) || connection.connectorName === name); }; const connected = (name: string) => ['connected', 'active'].includes(connectionFor(name)?.status.toLowerCase() ?? '');
 return <View style={{ gap: 8 }}>{summary && selected.length ? <Text style={[ui.detail, { textAlign: 'right' }]}>{selected.filter(connected).length} / {selected.length} 已连接</Text> : null}{selected.map(name => { const item = find(name); const connection = connectionFor(name); return <View key={name} style={ui.row}><View style={ui.icon}><Ionicons name={item?.icon ?? 'cube'} size={22} color="#287BFF" /></View><Pressable style={{ flex: 1 }} onPress={() => router.push(connection ? `/connections/${connection.id}` as never : '/connections/add' as never)}><Text style={ui.label}>{name}</Text><Text style={ui.detail}>{item?.description ?? '步骤关联的资源'}</Text></Pressable><Text style={{ fontSize: 12, color: connected(name) ? '#09A875' : '#8190A7' }}>{connections.isLoading ? '读取中' : connections.isError ? '状态未知' : connected(name) ? '✓ 已连接' : '尚未连接'}</Text>{onChange ? <Pressable accessibilityLabel={`移除${name}`} onPress={() => onChange(selected.filter(value => value !== name))}><Ionicons name="close-circle-outline" size={20} color="#8190A7" /></Pressable> : <Ionicons name="chevron-forward" size={18} color="#71809A" />}</View>; })}{!selected.length ? <Text style={ui.detail}>{summary ? '编辑步骤时添加所需资源' : '为这一步关联日历、通知、待办等资源'}</Text> : null}{onChange ? <Button secondary label="＋ 添加资源" onPress={() => { setPending(selected); setOpen(true); }} /> : null}<Modal visible={open} transparent animationType="slide" onRequestClose={() => setOpen(false)}><View style={{ flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(20,35,60,0.35)' }}><View style={[ui.card, { borderBottomLeftRadius: 0, borderBottomRightRadius: 0, padding: 24, maxHeight: '75%', paddingBottom: 32 }]}><View style={ui.line}><Text style={[ui.title, { flex: 1 }]}>选择所需资源</Text><Pressable accessibilityLabel="关闭资源选择" onPress={() => setOpen(false)}><Ionicons name="close" size={24} color="#61718C" /></Pressable></View><ScrollView>{options.map(item => <Pressable key={item.name} style={ui.row} onPress={() => setPending(pending.includes(item.name) ? pending.filter(name => name !== item.name) : [...pending, item.name])}><View style={ui.icon}><Ionicons name={item.icon} size={23} color="#287BFF" /></View><View style={{ flex: 1 }}><Text style={ui.label}>{item.name}</Text><Text style={ui.detail}>{item.description}</Text></View><Ionicons name={pending.includes(item.name) ? 'checkbox' : 'square-outline'} size={24} color="#287BFF" /></Pressable>)}</ScrollView>{connections.isError ? <Text style={ui.error}>暂时无法读取连接状态，选择后可继续配置连接。</Text> : null}<Button label="确认添加" onPress={() => { onChange?.(pending); setOpen(false); }} /></View></View></Modal></View>; }

