export const CONSUMER_SURFACES = ['schedule', 'plans', 'chat', 'resources', 'services'] as const;
export const TECHNICAL_TO_PRODUCT_DOMAIN: Readonly<Record<string, string>> = Object.freeze({ life: 'life', daily_life: 'life', living: 'living', family: 'family', pet: 'family', health: 'health', finance: 'finance', billing: 'finance', work: 'work', operations: 'work', content: 'work', study: 'study', information: 'information', travel: 'travel', social: 'social', entertainment: 'entertainment', housing: 'asset', vehicle: 'asset', device: 'asset', digital_account: 'asset', identity_docs: 'identity', government: 'identity', legal_contract: 'identity' });
export function productDomain(domain: string | null | undefined): string { return TECHNICAL_TO_PRODUCT_DOMAIN[domain ?? ''] ?? 'life'; }
export type ConsumerAction = { label: string; path: string };
export type SourceReference = { type: string; id: string };
export interface TimelineItem { allDay?: boolean; id: string; kind: 'USER_EVENT' | 'CALENDAR_EVENT' | 'PLAN_RUN' | 'TEMPORARY_TASK' | 'SERVICE_REQUEST' | 'ATTENTION' | 'REMINDER'; title: string; subtitle: string; scheduledAt: string | null; occurredAt: string; statusGroup: 'INCOMPLETE' | 'COMPLETED'; status: string; sourceRef: SourceReference; primaryAction: ConsumerAction }
export interface ResourceProjection { resourceId: string; kind: 'LOCAL' | 'CLOUD' | 'DEVICE' | 'INTERFACE'; name: string; summary: string; status: string; health: string; capabilities: string[]; reasons: string[]; lastVerifiedAt: string | null; sourceRef: SourceReference; primaryAction: ConsumerAction; capabilityState?:{associatedPlans?:{planId:string;title:string}[];canonicalKey?:string;group?:string;health?:string;key:string;userGrant:boolean;systemPermission:string;availability:string;implemented:boolean;readable:boolean}; capabilitySummary?:{total:number;available:number;items:Array<{key:string;name:string;operation:'read'|'execute'|'subscribe';usable:boolean}>}; evidenceRefs?:string[]; authority?:string }
export interface PlanLibraryItem { planId: string; title: string; summary: string; productDomain: string; status: 'RUNNING' | 'ATTENTION' | 'PAUSED' | 'ENDED'; nextRun: string | null; nextStep: string; sourceRef: SourceReference; primaryAction: ConsumerAction }

export interface ResourceNode {resourceId:string;kind:ResourceProjection['kind'];capabilities:readonly string[];sourceRef:SourceReference;authority:'NATIVE_OS'|'CONNECTION'|'TRUSTED_DEVICE'|'ACQUISITION';evidenceRefs:readonly string[];}
