import { useMutation } from '@tanstack/react-query';
import { Ionicons } from '@expo/vector-icons';
import { Link, router } from 'expo-router';
import { useState } from 'react';
import { ImageBackground, KeyboardAvoidingView, Platform, Pressable, ScrollView, StatusBar, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api, resolveAppEnv } from '../../src/api';
import { useAuthStore } from '../../src/auth-store';
import { ActionButton, workspaceColors as colors, radius, spacing, typography } from '../../src/design';
import { normalizeLoginIdentifier } from '../../src/login-identifier';
import type { SessionTokens } from '../../src/secure-token-store';

export default function LoginPage() {
  const setSession = useAuthStore((state) => state.setSession);
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [mode, setMode] = useState<'email' | 'phone'>('email');
  const [agreed, setAgreed] = useState(false);
  const login = useMutation({
    mutationFn: () => api<SessionTokens>('/auth/login', undefined, { method: 'POST', body: JSON.stringify({ email: normalizeLoginIdentifier(email, resolveAppEnv()), password }) }),
    onSuccess: async (tokens) => { await setSession(tokens); router.replace('/' as never); },
  });
  const canLogin = agreed && Boolean(email.trim() && password) && !login.isPending;
  return <ImageBackground source={require('../../assets/space-bg-light.png')} resizeMode="cover" style={styles.loginBackground}><View pointerEvents="none" style={styles.loginVeil} /><SafeAreaView style={styles.loginSafe}><StatusBar barStyle="dark-content" translucent backgroundColor="transparent" /><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.loginContent} keyboardShouldPersistTaps="handled">
    <View style={styles.loginBrand}><View style={styles.loginLogo}><Ionicons name="planet-outline" size={34} color="#FFFFFF" /></View><Text style={styles.loginBrandName}>懒人装甲</Text><Text style={styles.loginTagline}>让复杂的事变简单</Text></View>
    <View accessibilityRole="tablist" style={styles.modeTabs}><Pressable accessibilityRole="tab" accessibilityState={{ selected: mode === 'phone' }} onPress={() => setMode('phone')} style={[styles.modeTab, mode === 'phone' && styles.modeTabSelected]}><Text style={[styles.modeText, mode === 'phone' && styles.modeTextSelected]}>手机登录</Text></Pressable><Pressable accessibilityRole="tab" accessibilityState={{ selected: mode === 'email' }} onPress={() => setMode('email')} style={[styles.modeTab, mode === 'email' && styles.modeTabSelected]}><Text style={[styles.modeText, mode === 'email' && styles.modeTextSelected]}>邮箱登录</Text></Pressable></View>
    {mode === 'email' ? <View style={styles.loginForm}><View style={styles.compactInput}><Ionicons name="mail-outline" size={19} color={colors.textSecondary} /><TextInput style={styles.compactTextInput} accessibilityLabel="账号或邮箱" autoCapitalize="none" autoComplete="email" keyboardType="email-address" placeholder="请输入邮箱或账号" placeholderTextColor={colors.textMuted} value={email} onChangeText={setEmail} /></View><View style={styles.compactInput}><Ionicons name="lock-closed-outline" size={19} color={colors.textSecondary} /><TextInput style={styles.compactTextInput} accessibilityLabel="密码" autoComplete="current-password" secureTextEntry placeholder="请输入密码" placeholderTextColor={colors.textMuted} value={password} onChangeText={setPassword} /></View>{login.isError ? <Text style={styles.error}>没有登录成功，请检查账号和密码后重试。</Text> : null}<Pressable accessibilityRole="button" disabled={!canLogin} onPress={() => login.mutate()} style={[styles.loginButton, !canLogin && styles.loginButtonDisabled]}><Text style={styles.loginButtonText}>{login.isPending ? '登录中…' : '登录'}</Text></Pressable><Link href={'/auth/forgot-password' as never} style={styles.forgotLink}>忘记密码？</Link></View> : <View style={styles.phoneUnavailable}><Ionicons name="phone-portrait-outline" size={25} color={colors.textSecondary} /><Text style={styles.phoneUnavailableTitle}>手机验证码登录暂未接入</Text><Text style={styles.phoneUnavailableText}>当前请使用邮箱或账号密码登录，不会模拟发送验证码。</Text><Pressable onPress={() => setMode('email')} style={styles.switchEmail}><Text style={styles.switchEmailText}>使用邮箱登录</Text></Pressable></View>}
    <Pressable accessibilityRole="checkbox" accessibilityState={{ checked: agreed }} onPress={() => setAgreed((value) => !value)} style={styles.agreement}><View style={[styles.checkbox, agreed && styles.checkboxChecked]}>{agreed ? <Ionicons name="checkmark" size={13} color="#FFFFFF" /> : null}</View><Text style={styles.agreementText}>我已阅读并同意《用户协议》和《隐私政策》</Text></Pressable>
    <View style={styles.otherDivider}><View style={styles.dividerLine} /><Text style={styles.otherText}>其他方式登录</Text><View style={styles.dividerLine} /></View><View style={styles.otherMethods}><OtherLogin icon="logo-wechat" label="微信" /><OtherLogin icon="logo-apple" label="苹果" /><OtherLogin icon="ellipsis-horizontal" label="更多" /></View>
    <View style={styles.registerFooter}><Text style={styles.footerText}>第一次使用？</Text><Link href={'/auth/register' as never} style={styles.strongLink}>创建账号</Link></View>
  </ScrollView></KeyboardAvoidingView></SafeAreaView></ImageBackground>;
}

function OtherLogin({ icon, label }: { icon: React.ComponentProps<typeof Ionicons>['name']; label: string }) { return <View style={styles.otherMethod}><View style={styles.otherCircle}><Ionicons name={icon} size={22} color={colors.textSecondary} /></View><Text style={styles.otherLabel}>{label}</Text></View>; }

export function AuthPage({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) {
  return <SafeAreaView style={styles.safeArea}><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <View style={styles.topbar}>{router.canGoBack() ? <Pressable accessibilityRole="button" accessibilityLabel="返回" onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><Ionicons name="chevron-back" size={24} color={colors.text} /></Pressable> : <View style={styles.backPlaceholder} />}<View style={styles.brand}><View style={styles.logo}><Ionicons name="shield-checkmark-outline" size={20} color={colors.primary} /></View><Text style={styles.brandName}>懒人装甲</Text></View><View style={styles.topbarBalance} /></View>
    <View style={styles.intro}><Text style={styles.eyebrow}>账号</Text><Text style={styles.title}>{title}</Text><Text style={styles.subtitle}>{subtitle}</Text></View>
    <View style={styles.form}>{children}</View>
  </ScrollView></KeyboardAvoidingView></SafeAreaView>;
}

export const styles = StyleSheet.create({
  loginBackground: { flex: 1 }, loginVeil: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, backgroundColor: 'rgba(255,255,255,0.10)' }, loginSafe: { flex: 1, backgroundColor: 'transparent' }, loginContent: { flexGrow: 1, paddingHorizontal: spacing.xl, paddingTop: 54, paddingBottom: spacing.xxl }, loginBrand: { alignItems: 'center' }, loginLogo: { width: 66, height: 66, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(20,28,39,0.92)' }, loginBrandName: { color: colors.text, fontSize: 26, lineHeight: 34, fontWeight: '700', letterSpacing: 3, marginTop: spacing.md }, loginTagline: { ...typography.caption, color: colors.textSecondary, letterSpacing: 2, marginTop: 2 },
  modeTabs: { height: 48, flexDirection: 'row', padding: 3, marginTop: 42, borderRadius: 16, backgroundColor: 'rgba(232,240,249,0.72)' }, modeTab: { flex: 1, alignItems: 'center', justifyContent: 'center', borderRadius: 13 }, modeTabSelected: { backgroundColor: 'rgba(255,255,255,0.90)' }, modeText: { ...typography.caption, color: colors.textMuted, fontWeight: '600' }, modeTextSelected: { color: colors.text }, loginForm: { gap: spacing.md, marginTop: spacing.lg }, compactInput: { height: 54, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingHorizontal: spacing.md, borderWidth: 1, borderColor: 'rgba(255,255,255,0.72)', borderRadius: 16, backgroundColor: 'rgba(255,255,255,0.78)' }, compactTextInput: { flex: 1, height: 52, ...typography.body, color: colors.text }, loginButton: { height: 54, alignItems: 'center', justifyContent: 'center', marginTop: spacing.xs, borderRadius: 16, backgroundColor: colors.primary }, loginButtonDisabled: { backgroundColor: 'rgba(86,102,119,0.56)' }, loginButtonText: { ...typography.bodyStrong, color: '#FFFFFF' }, forgotLink: { ...typography.caption, color: colors.text, textAlign: 'center', marginTop: spacing.xs },
  phoneUnavailable: { minHeight: 194, alignItems: 'center', justifyContent: 'center', marginTop: spacing.lg, paddingHorizontal: spacing.xl, borderRadius: 14, backgroundColor: colors.accentSoft }, phoneUnavailableTitle: { ...typography.bodyStrong, color: colors.text, marginTop: spacing.sm }, phoneUnavailableText: { ...typography.caption, color: colors.textSecondary, textAlign: 'center', lineHeight: 19, marginTop: 3 }, switchEmail: { paddingHorizontal: spacing.lg, paddingVertical: 9, marginTop: spacing.md, borderRadius: 12, backgroundColor: colors.surface }, switchEmailText: { ...typography.caption, color: colors.text, fontWeight: '600' }, agreement: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, marginTop: spacing.lg }, checkbox: { width: 17, height: 17, borderRadius: 4, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border }, checkboxChecked: { backgroundColor: colors.primary, borderColor: colors.primary }, agreementText: { fontSize: 10, lineHeight: 15, color: colors.textSecondary },
  otherDivider: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, marginTop: 44 }, dividerLine: { flex: 1, height: StyleSheet.hairlineWidth, backgroundColor: colors.border }, otherText: { fontSize: 10, color: colors.textMuted }, otherMethods: { flexDirection: 'row', justifyContent: 'center', gap: 42, marginTop: spacing.lg }, otherMethod: { alignItems: 'center', gap: 7 }, otherCircle: { width: 48, height: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, otherLabel: { fontSize: 10, color: colors.textMuted }, registerFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.xs, marginTop: 36 },
  safeArea: { flex: 1, backgroundColor: colors.background }, flex: { flex: 1 }, content: { flexGrow: 1, paddingHorizontal: spacing.xl, paddingTop: spacing.sm, paddingBottom: spacing.xxxl },
  topbar: { minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, back: { width: 42, height: 42, marginLeft: -8, alignItems: 'center', justifyContent: 'center', borderRadius: 14 }, backPlaceholder: { width: 42, height: 42 }, topbarBalance: { width: 42 }, pressed: { opacity: 0.64 },
  brand: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, logo: { width: 36, height: 36, borderRadius: 12, backgroundColor: colors.successSoft, alignItems: 'center', justifyContent: 'center' }, brandName: { ...typography.bodyStrong, color: colors.text, fontWeight: '600' },
  intro: { marginTop: spacing.xxxl }, eyebrow: { ...typography.caption, color: colors.primary, fontWeight: '700', marginBottom: spacing.xs }, title: { ...typography.pageTitle, color: colors.text, fontSize: 28, lineHeight: 36, fontWeight: '600' }, subtitle: { ...typography.body, color: colors.textSecondary, fontSize: 15, lineHeight: 23, marginTop: spacing.sm }, form: { gap: spacing.sm, marginTop: spacing.xxl },
  fieldLabel: { ...typography.bodyStrong, color: colors.text, marginTop: spacing.xs }, input: { ...typography.body, minHeight: 56, color: colors.text, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, borderRadius: radius.md, paddingHorizontal: spacing.lg, paddingVertical: 14 },
  error: { ...typography.caption, color: colors.danger, lineHeight: 19 }, success: { ...typography.body, color: colors.textSecondary, lineHeight: 22 }, infoBlock: { gap: spacing.xs, borderLeftWidth: 3, borderLeftColor: colors.primary, paddingLeft: spacing.md }, infoTitle: { ...typography.bodyStrong, color: colors.text }, infoCopy: { ...typography.body, color: colors.textSecondary, lineHeight: 21 }, action: { marginTop: spacing.md }, textLink: { ...typography.bodyStrong, color: colors.primary, textAlign: 'center', marginTop: spacing.md },
  footer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.xs, marginTop: spacing.xl }, footerText: { ...typography.body, color: colors.textSecondary }, strongLink: { ...typography.bodyStrong, color: colors.primary },
});
