CREATE TABLE consumer_conversations (id binary(16) PRIMARY KEY, user_id binary(16) NOT NULL, mode varchar(16) NOT NULL, title varchar(160) NOT NULL, status varchar(24) NOT NULL, template_key varchar(120), plan_id binary(16), draft_id binary(16), version int NOT NULL DEFAULT 0, created_at datetime(6) NOT NULL, updated_at datetime(6) NOT NULL, INDEX consumer_conversations_user_idx (user_id, updated_at), FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (plan_id) REFERENCES plans(id), FOREIGN KEY (draft_id) REFERENCES creation_drafts(draft_id));
--> statement-breakpoint
CREATE TABLE consumer_messages (id binary(16) PRIMARY KEY, conversation_id binary(16) NOT NULL, request_id varchar(100) NOT NULL, role varchar(16) NOT NULL, content text NOT NULL, structured_payload json, context_refs json NOT NULL, model_id varchar(100), created_at datetime(6) NOT NULL, UNIQUE KEY consumer_messages_request_uq (conversation_id, request_id, role), INDEX consumer_messages_conversation_idx (conversation_id, created_at), FOREIGN KEY (conversation_id) REFERENCES consumer_conversations(id));
--> statement-breakpoint
CREATE TABLE external_service_references (id binary(16) PRIMARY KEY, user_id binary(16) NOT NULL, title varchar(160) NOT NULL, summary varchar(600) NOT NULL, source_platform varchar(100) NOT NULL, source_url varchar(2000) NOT NULL, provider_name varchar(160), price_snapshot varchar(100), thumbnail varchar(2000), category varchar(40) NOT NULL, import_method varchar(16) NOT NULL, created_at datetime(6) NOT NULL, updated_at datetime(6) NOT NULL, INDEX external_services_user_idx (user_id, created_at), FOREIGN KEY (user_id) REFERENCES users(id));
--> statement-breakpoint
CREATE TABLE consumer_service_requests (id binary(16) PRIMARY KEY, user_id binary(16) NOT NULL, offering_id binary(16) NOT NULL, request_id varchar(100) NOT NULL, scheduled_at datetime(6) NOT NULL, address varchar(600) NOT NULL, requirement varchar(600) NOT NULL, contact varchar(160) NOT NULL, status varchar(24) NOT NULL, version int NOT NULL DEFAULT 1, completed_at datetime(6), created_at datetime(6) NOT NULL, updated_at datetime(6) NOT NULL, UNIQUE KEY service_requests_user_request_uq (user_id, request_id), INDEX service_requests_schedule_idx (user_id, scheduled_at), FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (offering_id) REFERENCES service_offerings(id));
--> statement-breakpoint
CREATE TABLE consumer_service_request_events (id binary(16) PRIMARY KEY, request_id binary(16) NOT NULL, actor_user_id binary(16) NOT NULL, from_status varchar(24), to_status varchar(24) NOT NULL, created_at datetime(6) NOT NULL, INDEX service_request_events_idx (request_id, created_at), FOREIGN KEY (request_id) REFERENCES consumer_service_requests(id), FOREIGN KEY (actor_user_id) REFERENCES users(id));
