import { BadRequestException } from '@nestjs/common';
export function consumerPlanStatus(status: string, missing: boolean): 'RUNNING' | 'ATTENTION' | 'PAUSED' | 'ENDED' { if (['archived', 'completed'].includes(status)) return 'ENDED'; if (status === 'paused') return 'PAUSED'; if (missing || ['draft', 'error', 'failed', 'needs_attention'].includes(status)) return 'ATTENTION'; return status === 'active' ? 'RUNNING' : 'ATTENTION'; }
export function safeServiceUrl(value: string): string | null { try { const url = new URL(value); if (!['https:', 'http:'].includes(url.protocol) || url.username || url.password || !url.pathname.replace(/\//g, '') || /^(localhost|127\.|10\.|192\.168\.|169\.254\.|\[|0\.)/i.test(url.hostname)) return null; return url.href; } catch { return null; } }
export function requestTransitionAllowed(from: string, to: string): boolean { return ({ PENDING: ['BOOKED', 'CANCELLED'], BOOKED: ['IN_PROGRESS', 'CANCELLED'], IN_PROGRESS: ['COMPLETED', 'CANCELLED'] } as Record<string, string[]>)[from]?.includes(to) ?? false; }
export function temporaryConversationOutcome(result: string | undefined) {
  if (result === 'ANSWER') return { status: '已生成答复', statusGroup: 'COMPLETED' as const };
  if (result === 'ACTION_PROPOSAL') return { status: '一次性操作待确认', statusGroup: 'INCOMPLETE' as const };
 return { status: result === 'PLAN_DRAFT' ? '草案待确认' : result === 'CLARIFICATION_REQUIRED' ? '需要补充信息' : result === 'CONTEXT_UNAVAILABLE' ? '需要更新上下文' : result === 'MODEL_UNAVAILABLE' ? '模型暂不可用' : result === 'PLANNER_OUTPUT_INVALID' ? '草案校验未通过' : '正在分析', statusGroup: 'INCOMPLETE' as const };
}
export function dateWindow(date: string, timezone: string) { if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) throw new BadRequestException('日期格式应为 YYYY-MM-DD'); const midnight = new Date(`${date}T00:00:00Z`); if (Number.isNaN(midnight.getTime()) || midnight.toISOString().slice(0, 10) !== date) throw new BadRequestException('日期无效'); let formatter: Intl.DateTimeFormat; try { formatter = new Intl.DateTimeFormat('en-CA', { timeZone: timezone, year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', hourCycle: 'h23' }); } catch { throw new BadRequestException('时区无效'); } const convert = (utc: Date) => { let candidate = utc.getTime(); for (let i = 0; i < 3; i++) { const parts = Object.fromEntries(formatter.formatToParts(new Date(candidate)).map(p => [p.type, p.value])); const rendered = Date.UTC(+parts.year, +parts.month - 1, +parts.day, +parts.hour, +parts.minute, +parts.second); candidate += utc.getTime() - rendered; } return new Date(candidate); }; const next = new Date(midnight); next.setUTCDate(next.getUTCDate() + 1); return { start: convert(midnight), end: convert(next) }; }
