import type { INestApplication } from '@nestjs/common'; import type { Pool, RowDataPacket } from 'mysql2/promise'; import { createServer, type Server } from 'node:http'; import request from 'supertest';
import { afterAll, beforeAll, describe, expect, it } from 'vitest'; import { NOTION_CALLBACK_PATH } from '@lazy-armor/config'; import { NOTION_TRANSPORT, type NotionTransport } from '../src/providers/notion/notion-http.client';
import { NOTION_SCOPES, notionManifest } from '../src/providers/notion/notion-manifest'; import { auth, bootP2App, register, activatePlan, type Session } from './p2-test-helpers';
import type { ExecutionWorker } from '../src/execution/execution-worker.service'; import type { OutboxService } from '../src/execution/side-effect/outbox.service'; import type { OutboxWorker } from '../src/execution/side-effect/outbox-worker.service'; import { ReconciliationService } from '../src/execution/reconciliation.service';
import { ProviderCapabilityRegistryService } from '../src/provider-capabilities/provider-capability-registry.service';

describe.sequential('9E Notion over isolated TCP/MySQL; not real workspace acceptance', () => {
  let app: INestApplication; let pool: Pool; let server: Server; let owner: Session; let worker: ExecutionWorker; let connectionId: string; let mutations = 0; let disconnectUpdate = false; const hits: string[] = [];
  const unique = Date.now() + '-' + Math.random().toString(16).slice(2); const workspaceId = '10000000-0000-4000-8000-000000000002'; const botId = '10000000-0000-4000-8000-000000000001'; const ownerId = '10000000-0000-4000-8000-000000000003'; const dataSourceId = '20000000-0000-4000-8000-000000000001'; const pageId = '20000000-0000-4000-8000-000000000002';
  const pages = new Map<string, Record<string, unknown>>(); const keys = ['NOTION_OAUTH_CLIENT_ID', 'NOTION_OAUTH_CLIENT_SECRET', 'NOTION_OAUTH_REDIRECT_URI', 'REDIS_KEY_PREFIX'] as const; const saved = Object.fromEntries(keys.map((key) => [key, process.env[key]]));
  const source = () => ({ object: 'data_source', id: dataSourceId, last_edited_time: '2026-09-14T15:00:00Z', properties: { Name: { id: 'title', type: 'title' }, Done: { id: 'done', type: 'checkbox' } } });
  beforeAll(async () => {
    pages.set(pageId, page('Initial', false)); server = createServer(async (req, res) => { const chunks = []; for await (const chunk of req) chunks.push(chunk); const body = Buffer.concat(chunks).toString('utf8'); const url = new URL(req.url!, 'http://fixture'); hits.push(`${req.method} ${url.pathname}`); res.setHeader('content-type', 'application/json');
      if (url.pathname === '/v1/oauth/token') { res.end(JSON.stringify({ access_token: 'isolated-access-next', refresh_token: 'isolated-refresh-next', bot_id: botId, workspace_id: workspaceId, owner: { type: 'user', user: { id: ownerId } } })); return; }
      if (url.pathname === '/v1/oauth/introspect') { res.end(JSON.stringify({ active: true, scope: Object.values(NOTION_SCOPES).join(' ') })); return; }
      if (url.pathname === '/v1/oauth/revoke') { res.end('{}'); return; }
      if (url.pathname === '/v1/users/me') { res.end(JSON.stringify({ object: 'user', type: 'bot', id: botId })); return; }
      if (url.pathname === '/v1/search') { res.end(JSON.stringify({ results: [source(), pages.get(pageId)], has_more: false, next_cursor: null })); return; }
      if (url.pathname === '/v1/data_sources/' + dataSourceId) { res.end(JSON.stringify(source())); return; }
      if (url.pathname.endsWith('/query')) { res.end(JSON.stringify({ results: [...pages.values()], has_more: false, next_cursor: null })); return; }
      if (req.method === 'POST' && url.pathname === '/v1/pages') { mutations++; const input = JSON.parse(body); const createdId = '20000000-0000-4000-8000-' + String(100 + mutations).padStart(12, '0'); const created = { object: 'page', id: createdId, parent: input.parent, properties: decorate(input.properties), last_edited_time: new Date().toISOString() }; pages.set(createdId, created); res.end(JSON.stringify(created)); return; }
      const id = url.pathname.split('/').at(-1)!;
      if (req.method === 'PATCH' && pages.has(id)) { mutations++; const input = JSON.parse(body); const updated = { ...pages.get(id), properties: decorate(input.properties), last_edited_time: new Date().toISOString() }; pages.set(id, updated); if (disconnectUpdate) { req.socket.destroy(); return; } res.end(JSON.stringify(updated)); return; }
      if (pages.has(id)) { res.end(JSON.stringify(pages.get(id))); return; } res.statusCode = 404; res.end(JSON.stringify({ object: 'error', status: 404, code: 'object_not_found' }));
    });
    await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve)); const endpoint = 'http://127.0.0.1:' + (server.address() as { port: number }).port;
    process.env.NOTION_OAUTH_CLIENT_ID = 'isolated-notion-client'; process.env.NOTION_OAUTH_CLIENT_SECRET = 'isolated-notion-secret'; process.env.NOTION_OAUTH_REDIRECT_URI = 'https://api.example.test' + NOTION_CALLBACK_PATH; process.env.REDIS_KEY_PREFIX = 'lazy-armor-notion-' + unique;
    const transport: NotionTransport = (url, init) => { const parsed = new URL(url); return fetch(endpoint + parsed.pathname, init); }; ({ app, pool, worker } = await bootP2App('notion-' + unique, [{ token: NOTION_TRANSPORT, value: transport }]));
    await pool.query("UPDATE provider_capability_manifests SET status='SUPERSEDED',superseded_at=UTC_TIMESTAMP(6) WHERE provider_key='notion' AND revision IN (1,2)"); await pool.query("UPDATE provider_capability_manifests SET status='ACTIVE',superseded_at=NULL WHERE provider_key='notion' AND revision=3"); app.get(ProviderCapabilityRegistryService).installRevision(notionManifest); owner = await register(app, 'notion-' + unique + '@example.com', 'Notion owner');
  });
  afterAll(async () => { if (pool) { await pool.query("UPDATE provider_capability_manifests SET status='SUPERSEDED',superseded_at=UTC_TIMESTAMP(6) WHERE provider_key='notion' AND revision IN (2,3)"); await pool.query("UPDATE provider_capability_manifests SET status='ACTIVE',superseded_at=NULL WHERE provider_key='notion' AND revision=1"); }
    await app?.close(); await pool?.end(); if (server) await new Promise<void>((resolve) => server.close(() => resolve())); for (const key of keys) if (saved[key] === undefined) delete process.env[key]; else process.env[key] = saved[key]; });
  it('uses shared one-time OAuth state, grants actual scopes, and keeps direct writes closed', async () => { app.getHttpAdapter().getInstance().set('trust proxy', 'loopback'); const start = await request(app.getHttpServer()).post('/api/providers/notion/authorize').set(auth(owner.token)).send({}).expect(201); const state = new URL(start.body.authorizationUrl).searchParams.get('state')!;
    const replies = await Promise.all([1, 2, 3].map(() => request(app.getHttpServer()).get(NOTION_CALLBACK_PATH).query({ state, code: 'isolated' }).set('X-Forwarded-Proto', 'https'))); expect(replies.filter((r) => r.status === 200)).toHaveLength(1); connectionId = replies.find((r) => r.status === 200)!.body.connectionId;
    const [grants] = await pool.query<RowDataPacket[]>('SELECT capability_key FROM connection_capability_grants WHERE connection_id=UUID_TO_BIN(?)', [connectionId]); expect(grants).toHaveLength(4);
    const [health] = await pool.query<RowDataPacket[]>('SELECT capability_key,status,valid_until FROM provider_capability_health WHERE connection_id=UUID_TO_BIN(?) AND capability_key IN (?,?,?,?)', [connectionId, 'READ_PAGE', 'READ_DATA_SOURCE', 'CREATE_PAGE', 'UPDATE_PAGE']); expect(health, JSON.stringify(health)).toHaveLength(4); expect(health.every((row) => row.status === 'HEALTHY' && new Date(row.valid_until) > new Date()), JSON.stringify(health)).toBe(true);
    await request(app.getHttpServer()).post(`/api/connections/${connectionId}/invoke`).set(auth(owner.token)).send({ capability: 'CREATE_PAGE', requestId: unique, input: {} }).expect(403); expect(mutations).toBe(0); });
  it('publishes authenticated Page/DataSource observations into one versioned Truth identity', async () => { const replies = await Promise.all([1, 2, 3].map(() => request(app.getHttpServer()).post(`/api/providers/notion/connections/${connectionId}/observations`).set(auth(owner.token)).send({ capability: 'READ_DATA_SOURCE', resourceId: dataSourceId, includeRows: true, maxItems: 10 })));
    expect(replies.every((r) => r.status === 201), JSON.stringify({ bodies: replies.map((r) => r.body), hits })).toBe(true); const [truth] = await pool.query<RowDataPacket[]>("SELECT tr.resource_key,COUNT(trv.id) versions FROM truth_records tr JOIN truth_record_versions trv ON trv.truth_record_id=tr.id WHERE tr.user_id=UUID_TO_BIN(?) AND tr.resource_key IN ('Page','DataSource') GROUP BY tr.id", [owner.userId]); expect(truth).toHaveLength(2); expect(truth.every((row) => row.versions === 1)).toBe(true); });
  it('runs CREATE_PAGE through approval/Existing Execution and records read-back verification', async () => { const run = await approved('CREATE_PAGE', { parent: { type: 'data_source_id', id: dataSourceId }, properties: { Name: { type: 'title', value: 'Created' }, Done: { type: 'checkbox', value: true } } }); const outbox = app.get<OutboxService>('OUTBOX_SERVICE'); const dispatcher = app.get<OutboxWorker>('OUTBOX_WORKER'); const claimed = (await outbox.claim(1000, unique + '-create')).find((m) => m.id === run.messageId)!; await dispatcher.process(claimed);
    const [evidence] = await pool.query<RowDataPacket[]>("SELECT ve.result_state FROM verification_evidence ve JOIN side_effect_operations op ON op.id=ve.operation_id WHERE op.execution_id=UUID_TO_BIN(?)", [run.executionId]); expect(evidence.some((row) => row.result_state === 'SUCCEEDED')).toBe(true); expect(mutations).toBe(1); });
  it('does not repeat a possibly effected UPDATE and reconciles by read-back under concurrent claims', async () => { disconnectUpdate = true; const run = await approved('UPDATE_PAGE', { parent: { type: 'data_source_id', id: dataSourceId }, pageId, properties: { Name: { type: 'title', value: 'Updated' }, Done: { type: 'checkbox', value: true } } }); const outbox = app.get<OutboxService>('OUTBOX_SERVICE'); const dispatcher = app.get<OutboxWorker>('OUTBOX_WORKER'); const claims = (await Promise.all([outbox.claim(1000, unique + 'a'), outbox.claim(1000, unique + 'b')])).flat().filter((m) => m.id === run.messageId); expect(claims).toHaveLength(1); await Promise.all([dispatcher.process(claims[0]), dispatcher.process(claims[0])]); expect(mutations).toBe(2); disconnectUpdate = false;
    const [cases] = await pool.query<RowDataPacket[]>('SELECT BIN_TO_UUID(id) id FROM reconciliation_cases WHERE execution_id=UUID_TO_BIN(?)', [run.executionId]); expect(cases).toHaveLength(1); const reconciliation = app.get(ReconciliationService); const checks = (await Promise.all([reconciliation.claim(100), reconciliation.claim(100)])).flat().filter((v) => v.id === cases[0].id); expect(checks).toHaveLength(1); await reconciliation.process(checks[0]); expect(await reconciliation.get(owner.userId, cases[0].id)).toMatchObject({ status: 'RESOLVED', resultState: 'SUCCEEDED' }); await dispatcher.process(claims[0]); expect(mutations).toBe(2); });
  async function approved(capability: string, notionAction: Record<string, unknown>) { const plan = await request(app.getHttpServer()).post('/api/plans').set(auth(owner.token)).send({ name: capability + unique, domain: 'general', automationLevel: 'L2', sources: [{ sourceType: 'manual', config: {}, sortOrder: 0 }], triggers: [{ triggerType: 'manual', config: {}, sortOrder: 0 }], conditions: [], actions: [{ actionType: 'publish', connectionId, requiredCapability: capability, config: { visibility: 'private' }, stepOrder: 0 }] }).expect(201); await activatePlan(app, owner.token, plan.body.id);
    const execution = await request(app.getHttpServer()).post(`/api/plans/${plan.body.id}/executions`).set(auth(owner.token)).send({ requestId: unique + capability, triggerPayload: { notionAction } }).expect(201); await worker.processExecution(execution.body.id); const detail = await request(app.getHttpServer()).get(`/api/executions/${execution.body.id}`).set(auth(owner.token)).expect(200); expect(detail.body.status).toBe('waiting_approval'); await request(app.getHttpServer()).post('/api/approvals/' + detail.body.approvals[0].id + '/approve').set(auth(owner.token)).send({}).expect(201); await worker.processExecution(execution.body.id); const [messages] = await pool.query<RowDataPacket[]>("SELECT BIN_TO_UUID(id) id FROM outbox_messages WHERE JSON_UNQUOTE(JSON_EXTRACT(payload_json,'$.executionId'))=?", [execution.body.id]); expect(messages).toHaveLength(1); return { executionId: execution.body.id, messageId: messages[0].id }; }
  function page(name: string, done: boolean) { return { object: 'page', id: pageId, parent: { type: 'data_source_id', data_source_id: dataSourceId }, properties: decorate({ Name: { title: [{ type: 'text', text: { content: name } }] }, Done: { checkbox: done } }), last_edited_time: new Date().toISOString() }; }
  function decorate(properties: Record<string, Record<string, unknown>>) { return Object.fromEntries(Object.entries(properties).map(([key, value]) => [key, { id: key, type: Object.keys(value)[0], ...value }])); }
});
