import type {INestApplication} from '@nestjs/common';
import type {Pool} from 'mysql2/promise';
import request from 'supertest';
import {describe,it,expect,beforeAll,afterAll} from 'vitest';
import {auth,bootP2App,register,type Session} from './p2-test-helpers';
import {RuntimeTargetsService} from '../src/runtime-targets/runtime-targets.service';
import {newId} from '@lazy-armor/shared';
describe.sequential('V8.3 runtime targets',{timeout:90000},()=>{
 let app:INestApplication,pool:Pool,owner:Session,other:Session,deviceId:string;
 beforeAll(async()=>{const key=`v83-target-${Date.now()}`;({app,pool}=await bootP2App(key));owner=await register(app,`${key}@example.com`,'Owner');other=await register(app,`${key}-other@example.com`,'Other');deviceId=newId();await pool.query("INSERT INTO trusted_devices(id,user_id,device_id,key_id,public_key_spki,public_key_fingerprint,trust_level,status,last_proved_at,created_at,updated_at) VALUES(UUID_TO_BIN(?),UUID_TO_BIN(?),?,?,?,?,'key_proven','active',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[deviceId,owner.userId,deviceId,deviceId,'isolated-contract-key','a'.repeat(64)]);await pool.query("INSERT INTO device_heartbeats(id,user_id,trusted_device_id,device_id,online_state,last_heartbeat_at,created_at) VALUES(UUID_TO_BIN(?),UUID_TO_BIN(?),UUID_TO_BIN(?),?,'online',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[newId(),owner.userId,deviceId,deviceId]);});
 afterAll(async()=>{await app?.close();await pool?.end();});
 async function targets(){return (await request(app.getHttpServer()).get('/api/runtime-targets').set(auth(owner.token)).expect(200)).body;}
 it('registers owned backing idempotently under concurrent refresh',async()=>{const results=await Promise.all([targets(),targets(),targets()]);expect(results.map(r=>r[0].targetId)).toEqual([results[0][0].targetId,results[0][0].targetId,results[0][0].targetId]);expect(results[0][0].authorityEpoch).toBe(1);expect(results[0][0].manifestHash).toMatch(/^[a-f0-9]{64}$/);const target=results[0][0];await request(app.getHttpServer()).get(`/api/runtime-targets/${target.targetId}`).set(auth(other.token)).expect(404);expect((await request(app.getHttpServer()).get('/api/runtime-targets').set(auth(other.token)).expect(200)).body).toEqual([]);});
 it('rejects stale heartbeat without resetting epoch; fences hash and revoke',async()=>{const initial=(await targets())[0];await pool.query('UPDATE device_heartbeats SET last_heartbeat_at=DATE_SUB(UTC_TIMESTAMP(6),INTERVAL 1 HOUR) WHERE trusted_device_id=UUID_TO_BIN(?)',[deviceId]);const stale=(await targets())[0];expect(stale.onlineState).toBe('OFFLINE');expect(stale.authorityEpoch).toBe(initial.authorityEpoch);await expect(app.get(RuntimeTargetsService).assertCurrent(owner.userId,stale.targetId,stale.authorityEpoch,'0'.repeat(64))).rejects.toThrow('MANIFEST_HASH_MISMATCH');await pool.query("UPDATE trusted_devices SET status='revoked' WHERE id=UUID_TO_BIN(?)",[deviceId]);const revoked=(await targets())[0];expect(revoked.authorityEpoch).toBe(initial.authorityEpoch+1);expect(revoked.health).toBe('UNAVAILABLE');await expect(app.get(RuntimeTargetsService).assertCurrent(owner.userId,revoked.targetId,initial.authorityEpoch)).rejects.toThrow('STALE_AUTHORITY_EPOCH');expect((await targets())[0].authorityEpoch).toBe(revoked.authorityEpoch);});
 it('re-enrollment changes epoch even for the same signing key',async()=>{const previous=(await targets())[0];await pool.query("UPDATE trusted_devices SET status='active',last_proved_at=UTC_TIMESTAMP(6) WHERE id=UUID_TO_BIN(?)",[deviceId]);const restored=(await targets())[0];expect(restored.authorityEpoch).toBe(previous.authorityEpoch+1);});
});
